# ============================================================
# SIGMASCOPE — Dictionnaire de traduction FRANÇAIS
# ============================================================

TRANSLATIONS = {

    # ── Langue ──────────────────────────────────────────────
    "lang_selector_label": "🌐 Langue / Language / Dil",
    "lang_fr": "🇫🇷 Français",
    "lang_en": "🇬🇧 English",
    "lang_tr": "🇹🇷 Türkçe",

    # ── Sidebar ──────────────────────────────────────────────
    "sidebar_title":        "🚀 SigmaScope by jp",
    "sidebar_nav":          "### 🗂️ Navigation",
    "sidebar_indices":      "**📂 Indices chargés**",
    "sidebar_no_index":     "⚠️ Aucun indice chargé.\nAllez dans ⚙️ Configuration.",
    "sidebar_valeurs":      "valeurs",
    "sidebar_stop":         "⏹️ Arrêter l'application",
    "sidebar_stop_help":    "Stoppe le serveur Streamlit",
    "sidebar_stopping":     "Arrêt en cours…",

    # ── Pages navigation ─────────────────────────────────────
    "page_presentation":    "🏠 Présentation",
    "page_analyse":         "📈 Analyse valeur",
    "page_watchlists":      "⭐ Watchlists",
    "page_comparaison":     "🔀 Comparaison de valeurs",
    "page_screener_sigma":  "🔭 Screener Sigma",
    "page_screener_multi":  "🎛️ Screener multi-critères",
    "page_explications":    "📖 Explications",
    "page_configuration":   "⚙️ Configuration",

    # ── Page Présentation — Hero ─────────────────────────────
    "hero_tagline":         "La plateforme d'analyse boursière quantitative tout-en-un",
    "hero_tagline2":        "Régression log · Analyse fondamentale · Screener · Valorisation DCF",
    "hero_version":         "✨ Version 24 — par jp",
    "hero_pp_compat":       "🤝 Compatible avec",
    "hero_pp_desc":         "— import direct de votre compte-titres (fichier XML)",

    # ── Page Présentation — Features ─────────────────────────
    "feat_title":           "### 🧩 Fonctionnalités principales",
    "feat_open_analyse":    "→ Ouvrir l'Analyse valeur",
    "feat_open_watchlist":  "→ Ouvrir les Watchlists",
    "feat_open_comparaison":"→ Ouvrir la Comparaison",
    "feat_open_screener_s": "→ Ouvrir le Screener Sigma",
    "feat_open_screener_m": "→ Ouvrir le Screener multi-critères",
    "feat_open_valorisation":"→ Voir dans Analyse valeur",

    # ── Page Présentation — Stats badges ────────────────────
    "stat_modules":         "Modules d'analyse",
    "stat_indices":         "Indices chargés",
    "stat_tickers":         "Tickers pré-chargés (∞ via Yahoo Finance)",
    "stat_methods":         "Méthodes de valorisation",
    "stat_sigma_zones":     "Zones sigma détectées",

    # ── Page Présentation — Quick start ─────────────────────
    "quickstart_title":     "### 🚀 Démarrage rapide",
    "sigma_zones_title":    "### 📐 Comprendre les zones sigma",

    # ── Page Présentation — Roadmap ──────────────────────────
    "roadmap_expander":     "🛠️ Roadmap & reste à faire",
    "roadmap_title":        "#### 🚧 En cours de développement / à venir",
    "roadmap_legend_high":  "🔴 Priorité haute",
    "roadmap_legend_study": "🟢 À l'étude",
    "roadmap_caption":      "💡 Dites-moi ce qui vous serait le plus utile dans la section **Suggestions & améliorations** ci-dessous !",
    "roadmap_item1_title":  "Correction / vérification du calcul du juste prix",
    "roadmap_item1_desc":   "Révision approfondie des méthodes **DCF, Gordon-Shapiro, Multiples et ANR** — vérification de la cohérence des formules, des hypothèses par défaut et des résultats avec les standards de valorisation financière.",
    "roadmap_item2_title":  "Authentification Google",
    "roadmap_item2_desc":   "Remplacement du token anonyme par un **vrai compte Google** — pour retrouver ses watchlists depuis n'importe quel appareil. Laissez-moi un commentaire si c'est important pour vous 👇",
    "roadmap_item3_title":  "Export des données",
    "roadmap_item3_desc":   "Export des watchlists et résultats d'analyse en **CSV / Excel**. Laissez-moi un commentaire si vous en avez besoin 👇",
    "roadmap_item4_title":  "Screener avancé",
    "roadmap_item4_desc":   "Ajout de filtres techniques (RSI, Bollinger) dans le screener multi-critères. Laissez-moi un commentaire si c'est utile pour vous 👇",
    "roadmap_item5_title":  "Stabilité Yahoo Finance",
    "roadmap_item5_desc":   "Le rate limiting de Yahoo Finance peut causer des erreurs intermittentes. Une API officielle de remplacement est à l'étude. Laissez-moi un commentaire si vous rencontrez souvent ce problème 👇",
    "roadmap_item6_title":  "Migration vers un vrai site web",
    "roadmap_item6_desc":   "Si l'usage le justifie, une migration vers une **application web complète** (FastAPI + React) est envisagée. Votez ci-dessous et laissez un commentaire 👇",

    # ── Page Présentation — Stats & notation ─────────────────
    "stats_expander":           "📊 Vie & statistiques de l'application",
    "stats_users":              "Utilisateurs uniques",
    "stats_sessions":           "Sessions totales",
    "stats_duration":           "Durée moy. session",
    "stats_rating":             "avis",
    "stats_saas_vote":          "Vote migration site web",
    "stats_rating_title":       "#### ⭐ Notez l'application",
    "stats_your_note":          "Votre note",
    "stats_saas_question":      "Faut-il convertir SigmaScope en un vrai site web ?",
    "stats_saas_yes":           "✅ Oui, convertir en vrai site web",
    "stats_saas_no":            "❌ Non, l'app Streamlit me suffit",
    "stats_save_btn":           "💾 Enregistrer mon avis",
    "stats_save_ok":            "✅ Merci ! Note : {stars} — Vote SaaS : {vote}",
    "stats_save_oui":           "Oui",
    "stats_save_non":           "Non",
    "stats_save_err":           "❌ Erreur lors de la sauvegarde.",

    # ── Page Présentation — Suggestions ──────────────────────
    "feedback_expander":        "💬 Suggestions & améliorations",
    "feedback_title":           "#### 📝 Laisser un message",
    "feedback_visibility":      "Visibilité du message",
    "feedback_public":          "🌐 Public — visible par tous",
    "feedback_private":         "🔒 Privé — visible uniquement par l'administrateur",
    "feedback_caption_private": "🔒 Ce message sera visible uniquement par l'administrateur.",
    "feedback_caption_public":  "🌐 Ce message sera visible par tous les utilisateurs.",
    "feedback_placeholder":     "Ex : Ajouter un indicateur MACD, améliorer la page screener...",
    "feedback_send_btn":        "📤 Envoyer",
    "feedback_ok_private":      "✅ Message privé envoyé à l'administrateur, merci !",
    "feedback_ok_public":       "✅ Message public envoyé, merci !",
    "feedback_err":             "❌ Erreur lors de l'envoi.",
    "feedback_empty":           "⚠️ Le message ne peut pas être vide.",
    "feedback_community_title": "#### 💡 Suggestions de la communauté",
    "feedback_none":            "Aucune suggestion pour l'instant — soyez le premier !",

    # ── Footer ───────────────────────────────────────────────
    "footer_text":  "⚡ SigmaScope utilise <strong style=\"color:#4C9BE8;\">Yahoo Finance</strong> comme source de données · Conçu pour l'analyse quantitative · <em>Pas un conseil en investissement</em>",

    # ── Page Analyse valeur ───────────────────────────────────
    "analyse_title":            "📈 Analyse valeur",
    "analyse_params_expander":  "🔍 Paramètres d'analyse",
    "analyse_ticker_label":     "Ticker / Société",
    "analyse_ticker_help":      "Recherche filtrante sur tous les indices chargés",
    "analyse_ticker_placeholder":"Tapez un ticker (AAPL) ou un nom (Apple)…",
    "analyse_ticker_manual":    "Ticker manuel",
    "analyse_ticker_manual_ph": "ex : AAPL, BNP.PA…",
    "analyse_indice_label":     "Choisir un indice / watchlist",
    "analyse_composant_label":  "Composant ({n} valeurs)",
    "analyse_no_index":         "⚠️ Aucune donnée. Allez dans ⚙️ Configuration.",
    "analyse_choose_index":     "— choisir un indice d'abord —",
    "analyse_period_label":     "Période",
    "analyse_ticker_selected":  "Ticker sélectionné :",
    "analyse_launch_btn":       "🚀 Lancer l'Analyse",
    "analyse_loading":          "Chargement des données…",
    "analyse_no_data":          "Aucune donnée disponible pour ce ticker.",
    "analyse_error":            "Erreur : {e}",
    "analyse_configure_first":  "👆 Configurez un ticker ci-dessus puis cliquez sur **🚀 Lancer l'Analyse**.",

    # ── Analyse — sous-sections ───────────────────────────────
    "analyse_tech_expander":    "📊 Analyse Technique",
    "analyse_fair_expander":    "💰 Prix Juste Historique",
    "analyse_score_expander":   "📊 Scorecard Fondamental & Score Global",
    "analyse_histo_expander":   "📊 Historique des Indicateurs Fondamentaux",
    "analyse_info_expander":    "🏢 Informations sur la société",
    "analyse_trend_expander":   "📈 Analyse de Tendance",
    "analyse_adv_params":       "⚙️ Paramètres avancés",

    # ── Analyse — Technique ───────────────────────────────────
    "tc_period_warning":        "⚠️ Période limitée à **{period}** pour la granularité {interval}.",
    "tc_no_data":               "Pas de données disponibles pour ce ticker.",
    "tc_chart_err":             "Erreur chargement graphique technique : {e}",

    # ── Analyse — Prix Juste ──────────────────────────────────
    "fv_no_data":               "ℹ️ Données insuffisantes pour calculer le prix juste avec cette méthode ({method}).",
    "fv_no_fetch":              "⚠️ Impossible de récupérer les données pour calculer le prix juste.",

    # ── Watchlists ────────────────────────────────────────────
    "wl_title":                 "⭐ Mes Watchlists",
    "wl_info":                  "🔑 **Vos watchlists sont sauvegardées** dans une base de données sécurisée, identifiées par un token anonyme unique lié à votre navigateur (token : `{uid}`).  \n📌 **Marquez cette page en favori** pour retrouver vos watchlists depuis n'importe quand — l'URL contient votre token.  \n⚠️ **Expiration** : si vous ne revenez pas pendant **30 jours**, vos watchlists seront automatiquement supprimées de la base de données.",
    "wl_manage_expander":       "🗂️ Gestion des watchlists",
    "wl_active_label":          "📋 Watchlist active",
    "wl_new_btn":               "➕ Nouvelle",
    "wl_delete_btn":            "🗑️ Supprimer",
    "wl_delete_help":           "Supprimer la watchlist '{name}'",
    "wl_import_btn":            "📥 Importer",
    "wl_import_help":           "Importer un compte titre depuis Portfolio Performance (.xml)",
    "wl_delete_confirm_msg":    "⚠️ Supprimer la watchlist **{name}** et toutes ses entrées ?",
    "wl_delete_confirm_btn":    "🗑️ Confirmer la suppression",
    "wl_delete_cancel_btn":     "❌ Annuler",
    "wl_autosave":              "💾 **{name}** — sauvegarde automatique",
    "wl_add_expander":          "➕ Ajouter une action manuellement",
    "wl_add_ticker_label":      "Ticker",
    "wl_add_ticker_ph":         "ex : AAPL, BNP.PA",
    "wl_add_btn":               "➕ Ajouter",
    "wl_add_ok":                "✅ {ticker} ajouté à la watchlist !",
    "wl_add_duplicate":         "{ticker} est déjà dans la watchlist.",
    "wl_add_empty":             "Entrez un ticker.",
    "wl_empty_info":            "👆 Votre watchlist est vide. Ajoutez des actions via le bouton **⭐ Watchlist** présent sur toutes les pages, ou manuellement ci-dessus.",
    "wl_refresh_btn":           "🔄 Rafraîchir les données",
    "wl_data_errors":           "⚠️ Données indisponibles pour : {tickers}",
    "wl_analyse_tip":           "💡 Cochez **📈** sur la gauche pour lancer l'analyse individuelle du ticker",
    "wl_sigma_expander":        "📈 Aperçu graphique de la watchlist (positions sigma)",
    "wl_pru_expander":          "💰 Aperçu graphique de la watchlist (écart cours / PRU)",
    "wl_manage2_expander":      "⚙️ Gestion de la watchlist",
    "wl_remove_tip":            "💡 Cochez **🗑️ Retirer** pour supprimer une action de la watchlist",
    "wl_edit_expander":         "✏️ Ajouter une note / prix d'achat",
    "wl_save_edit_btn":         "💾 Enregistrer",
    "wl_edit_ok":               "✅ Modifié.",
    "wl_sigma_no_data":         "Données sigma indisponibles.",
    "wl_pru_no_data":           "Aucun prix d'achat renseigné dans cette watchlist.",

    # ── Comparaison ───────────────────────────────────────────
    "comp_title":               "🔀 Comparaison de valeurs (Peer Analysis)",
    "comp_params_expander":     "🔍 Paramètres de comparaison",
    "comp_selected":            "**Actions sélectionnées :** {tickers}",
    "comp_no_data":             "Aucune donnée disponible.",
    "comp_table_title":         "📋 Tableau de performance",
    "comp_tip":                 "💡 Cochez **📈 Analyser** pour l'analyse individuelle · Cochez **⭐ Watchlist** pour ajouter/retirer",
    "comp_configure_first":     "👆 Sélectionnez des actions puis cliquez sur **📊 Comparer**.",

    # ── Screener Sigma ────────────────────────────────────────
    "screener_sigma_title":     "🔭 Screener Sigma — Scanner les actions d'un indice",
    "screener_sigma_params":    "🔍 Paramètres du scan",
    "screener_sigma_no_index":  "⚠️ Aucun indice chargé. Allez dans ⚙️ Configuration.",
    "screener_sigma_launch":    "🔍 Lancer le scan",
    "screener_sigma_scanning":  "🔄 Scan de **{n}** actions de **{index}** sur **{period}** — zones : **{zones}**",
    "screener_sigma_errors":    "⚠️ Données indisponibles : {tickers}",
    "screener_sigma_no_result": "Aucune action trouvée pour les zones sélectionnées.",
    "screener_sigma_found":     "✅ **{n} action(s) trouvée(s)**  •  {index}  •  {period}",
    "screener_sigma_tip":       "💡 Cochez **📈 Analyser** pour lancer l'analyse · Cochez **⭐ WL** pour ajouter/retirer de la watchlist",
    "screener_sigma_charts":    "📈 Graphiques — {n} action(s)",
    "screener_sigma_log_warn":  "⚠️ Variation % incompatible avec l'échelle log",
    "screener_sigma_select_zone":"👆 Cochez au moins une zone puis cliquez sur **🔍 Lancer le scan**.",

    # ── Screener Multi-critères ───────────────────────────────
    "screener_multi_title":     "🎛️ Screener multi-critères",
    "screener_multi_params":    "🔍 Paramètres du screener",
    "screener_multi_no_index":  "⚠️ Aucun indice chargé. Allez dans ⚙️ Configuration.",
    "screener_multi_launch":    "🚀 Lancer le screener",
    "screener_multi_reset":     "↺ Réinitialiser les filtres",
    "screener_multi_no_sigma":  "ℹ️ Aucune zone sigma sélectionnée = toutes les zones acceptées.",
    "screener_multi_scanning":  "🔄 Scan de **{n}** actions de **{index}** — chargement des données…",
    "screener_multi_errors":    "⚠️ Erreurs sur : {tickers}",

    # ── Page Explications ─────────────────────────────────────
    "explain_title":            "📖 Guide des indicateurs & méthodes de valorisation",
    "explain_scoring_title":    "### 📊 Les Indicateurs de Scoring",
    "explain_valuation_title":  "### 💰 Valorisation : Comment calculer le Prix Juste d'une Action ?",
    "explain_params_title":     "### ⚙️ Guide des Paramètres de Valorisation",
    "explain_sensitivity_cap":  "💡 Les cases avec **augmente fortement** sont les paramètres les plus sensibles — à tester en scénario pessimiste/optimiste avant toute décision d'investissement.",

    # ── Page Configuration ────────────────────────────────────
    "config_title":             "⚙️ Configuration — Gestion des indices",
    "config_indices_title":     "📊 État des indices chargés",
    "config_preview_title":     "🔍 Aperçu des composants",
    "config_preview_select":    "Afficher les composants de",
    "config_choose_index":      "-- Choisir un indice --",
    "config_no_index":          "ℹ️ Aucun indice chargé. Connectez-vous en mode administrateur pour mettre à jour.",
    "config_admin_title":       "🔐 Administration",
    "config_admin_caption":     "Cette section est réservée à l'administrateur.",
    "config_admin_pwd_ph":      "••••••••",
    "config_admin_login_btn":   "🔑 Accéder",
    "config_admin_err":         "❌ Mot de passe incorrect.",
    "config_admin_ok":          "✅ Mode administrateur activé",
    "config_admin_logout":      "🔓 Déconnexion",
    "config_wiki_expander":     "🔄 Mise à jour des indices Wikipedia",
    "config_wiki_desc":         "Rechargez les composants des indices boursiers depuis Wikipedia.",
    "config_wiki_select":       "Indice à mettre à jour",
    "config_wiki_none":         "-- Aucun --",
    "config_wiki_btn":          "🔄 Mettre à jour",
    "config_wiki_btn_help":     "Recharge cet indice depuis Wikipedia",
    "config_wiki_source":       "🌐 Source :",
    "config_wiki_ok":           "✅ {n} composants sauvegardés pour {label}.",
    "config_wiki_err":          "Erreur scraping : {e}",
    "config_wiki_select_first": "Sélectionnez d'abord un indice.",
    "config_wiki_loading":      "Chargement {label}…",
    "config_sys_expander":      "ℹ️ Informations système",
    "config_cache_btn":         "🧹 Purger le cache market (> 2h)",
    "config_cache_ok":          "✅ Cache purgé.",
    "config_private_expander":  "🔒 Messages privés des utilisateurs",
    "config_private_none":      "Aucun message privé pour l'instant.",
    "config_purge_expander":    "🗑️ Nettoyage des watchlists inactives",
    "config_purge_caption":     "Supprime les watchlists (et leurs contenus) des utilisateurs qui ne se sont pas connectés depuis plus de 30 jours. ⚠️ Opération irréversible.",
    "config_purge_btn":         "🗑️ Purger les watchlists inactives (> 30j)",
    "config_purge_ok":          "✅ {n} watchlist(s) inactive(s) supprimée(s).",
    "config_purge_none":        "ℹ️ Aucune watchlist inactive à supprimer.",

    # ── Import Portfolio Performance ──────────────────────────
    "pp_dialog_title":          "📥 Importer depuis Portfolio Performance",
    "pp_step1":                 "📂 Chargement",
    "pp_step2":                 "🏦 Compte titre",
    "pp_step3":                 "✅ Confirmation",
    "pp_upload_label":          "**Charger le fichier XML Portfolio Performance**",
    "pp_upload_caption":        "Menu *Fichier → Enregistrer sous…* dans Portfolio Performance.",
    "pp_upload_info":           "👆 Sélectionnez votre fichier Portfolio Performance (.xml) ci-dessus.",
    "pp_upload_close":          "❌ Fermer",
    "pp_upload_err":            "❌ Erreur d'analyse : {e}",
    "pp_select_label":          "**Choisir le compte titre à importer**",
    "pp_select_account":        "Compte titre",
    "pp_select_pru_note":       "ℹ️ Les PRU sont en EUR (devise Portfolio Performance) et seront importés tels quels.",
    "pp_next_btn":              "▶️ Suivant",
    "pp_back_btn":              "◀️ Retour",
    "pp_cancel_btn":            "❌ Annuler",
    "pp_confirm_label":         "**Nommer la watchlist et confirmer l'import**",
    "pp_wl_name_label":         "Nom de la watchlist",
    "pp_wl_name_help":          "Une nouvelle watchlist sera créée avec ce nom (ou remplacée si elle existe déjà).",
    "pp_wl_exists":             "⚠️ La watchlist **{name}** existe déjà — son contenu sera **remplacé**.",
    "pp_wl_new":                "✨ Une nouvelle watchlist **{name}** sera créée.",
    "pp_import_btn":            "📥 Importer",
    "pp_import_empty_name":     "Le nom ne peut pas être vide.",
    "pp_import_ok":             "✅ {n} position(s) importées dans **{name}** !",

    # ── Watchlist dialog ──────────────────────────────────────
    "wl_dialog_title":          "🗂️ Dans quelle watchlist ajouter ce ticker ?",
    "wl_dialog_add_label":      "**Ajouter `{ticker}`** ({company}) à la watchlist :",
    "wl_dialog_target":         "Watchlist cible",
    "wl_dialog_already":        "⚠️ `{ticker}` est déjà dans **{name}**.",
    "wl_dialog_add_btn":        "✅ Ajouter",
    "wl_dialog_cancel_btn":     "❌ Annuler",
    "wl_dialog_add_ok":         "⭐ {ticker} ajouté à **{name}** !",
    "wl_dialog_remove_msg":     "**Retirer `{ticker}`** de la watchlist **{name}** ?",
    "wl_dialog_remove_btn":     "🗑️ Retirer",
    "wl_dialog_remove_ok":      "❌ {ticker} retiré de la watchlist",
    "wl_btn_add":               "⭐ Watchlist",
    "wl_btn_in":                "✅ Watchlist",
    "wl_btn_add_help":          "Ajouter à la watchlist ({name})",
    "wl_btn_remove_help":       "Retirer de la watchlist ({name})",

    # ── Supabase / connexion ──────────────────────────────────
    "supabase_err":             "❌ Connexion Supabase impossible : {e}",

    # ── Général ───────────────────────────────────────────────
    "min_suffix":               "min",
    "values_suffix":            "valeurs",
    "loading":                  "Chargement…",
    "error_prefix":             "Erreur : ",
    "analyse_launch_btn": "🚀 Lancer l'Analyse",
    "analyse_period_default": "10 Ans",
    "analyse_data_not_found": "Données introuvables pour ce ticker.",
    "analyse_loading_fundamentals": "Chargement des données fondamentales…",
    "analyse_ticker_selected_html": "Ticker sélectionné :",
    "analyse_yahoo_link": "Voir sur Yahoo Finance →",
    "analyse_position_sigma": "📍 Position actuelle :",
    "chart_period_label": "Période",
    "chart_yaxis_label": "Échelle Y",
    "chart_yaxis_linear": "Linéaire",
    "chart_yaxis_log": "Logarithmique",
    "chart_yaxis_help": "Linéaire : valeurs absolues  |  Logarithmique : mieux adapté aux grandes périodes",
    "chart_display_label": "Affichage Y",
    "chart_display_cours": "Cours",
    "chart_display_pct": "Variation %",
    "chart_display_help": "Cours : prix brut  |  Variation % : performance depuis le début de la période",
    "chart_display_log_disabled": "  ⚠️ Désactivé en échelle logarithmique",
    "chart_cours_title": "Cours",
    "tc_period_section": "**Période**",
    "tc_granularity_section": "**Granularité**",
    "tc_indicators_section": "**Indicateurs**",
    "tc_ma_label": "Moyennes mobiles",
    "tc_bb_label": "Bollinger",
    "tc_rsi_label": "RSI",
    "tc_volume_label": "Volume",
    "tc_ma_periods_section": "**Périodes MM**",
    "tc_bb_period_label": "Période BB",
    "tc_bb_std_label": "Écart-type BB",
    "tc_options_section": "**Options**",
    "tc_hide_gaps_label": "Masquer sauts",
    "tc_hide_gaps_help": "Supprime les trous sur l'axe X correspondant aux plages où le marché est clos (nuits, weekends, jours fériés)",
    "fv_method_label": "Méthode de valorisation",
    "fv_granularity_label": "Granularité",
    "fv_gran_monthly": "Mensuelle",
    "fv_gran_weekly": "Hebdomadaire",
    "fv_gran_yearly": "Annuelle",
    "fv_overlay_label": "Superposer le cours réel",
    "fv_auto_label": "Méthode automatique",
    "fv_auto_help": "Sélectionne automatiquement : {method}",
    "fv_suggested": "Méthode suggérée :",
    "fv_adv_params_caption": "Les paramètres grisés ne s'appliquent pas à la méthode sélectionnée. Les valeurs par défaut sont estimées automatiquement d'après le beta, la dette et le secteur du titre.",
    "fv_wacc_label": "WACC k (%)",
    "fv_g_label": "Croissance perpétuelle g (%)",
    "fv_k_gs_label": "Rendement exigé Gordon (%)",
    "fv_horizon_label": "Horizon DCF (ans)",
    "fv_calc_spinner": "Calcul du prix juste…",
    "fv_dcf_only": "⚠️ DCF uniquement",
    "fv_gordon_only": "⚠️ Gordon-Shapiro uniquement",
    "fv_gap_overvalued": "Surévalué de {pct:.1f}%",
    "fv_gap_undervalued": "Sous-évalué de {pct:.1f}%",
    "wl_create_name_label": "Nom de la nouvelle watchlist",
    "wl_create_btn": "✅ Créer",
    "wl_create_cancel": "Annuler",
    "wl_name_empty_err": "Le nom ne peut pas être vide.",
    "wl_name_exists_err": "Ce nom existe déjà.",
    "wl_created_ok": "✅ Watchlist **{name}** créée !",
    "wl_deleted_ok": "✅ Watchlist supprimée.",
    "wl_loading_data": "Chargement des données…",
    "wl_loading_ticker": "Chargement {ticker}…",
    "wl_col_ticker": "Ticker",
    "wl_col_company": "Société",
    "wl_col_date": "Date ajout",
    "wl_col_note": "Note",
    "wl_col_pru": "PRU (€)",
    "wl_col_price": "Cours (€)",
    "wl_col_change": "Var. J. (%)",
    "wl_col_sigma": "Position σ",
    "wl_col_score": "Score",
    "wl_col_roic": "ROIC (%)",
    "wl_col_revenue": "Croiss. CA (%)",
    "wl_col_fcfm": "Marge FCF (%)",
    "wl_col_debt": "Dette/FCF",
    "wl_col_peg": "PEG",
    "wl_col_pru_pct": "Écart PRU (%)",
    "wl_col_remove": "🗑️ Retirer",
    "wl_note_placeholder": "Note libre…",
    "wl_pru_placeholder": "Prix d'achat…",
    "wl_edit_ok": "✅ Modifié.",
    "wl_sigma_chart_title": "Position sigma — {period}",
    "wl_pru_chart_title": "Écart cours actuel (en €) / Prix d'achat PRU (en €)",
    "wl_progress_init": "Chargement des données…",
    "wl_ticker_manual_label": "Ajouter un ticker manuellement",
    "wl_ticker_ph": "ex : AAPL, MC.PA, ^GSPC…",
    "wl_period_select": "Horizon temporel",
    "wl_add_from_index": "Ajouter depuis les indices / watchlists chargés",
    "wl_add_from_index_help": "Les lignes '── Sélectionner tout : … ──' ajoutent toutes les actions. Les entrées ⭐ sont vos watchlists.",
    "wl_compare_btn": "📊 Comparer",
    "wl_load_market_data": "Chargement des données de marché…",
    "wl_best_stock": "🥇 Meilleure valeur",
    "wl_worst_stock": "📉 Moins bonne valeur",
    "wl_col_name": "Nom",
    "wl_col_perf": "Performance",
    "wl_col_vol": "Volatilité ann.",
    "wl_col_drawdown": "Max Drawdown",
    "wl_col_analyse": "📈 Analyser",
    "wl_norm_price": "Prix normalisé (base 1)",
    "wl_no_data_comp": "Données introuvables pour : {tickers}",
    "screener_sigma_period_label": "📅 Période d'analyse",
    "screener_sigma_index_label": "📂 Indice / Watchlist à scanner",
    "screener_sigma_index_help": "Les entrées ⭐ correspondent à vos watchlists",
    "screener_sigma_zones_title": "**🎯 Zones à rechercher** *(cochez une ou plusieurs zones)*",
    "screener_sigma_col_ticker": "Ticker",
    "screener_sigma_col_company": "Société",
    "screener_sigma_col_sigma": "Position σ",
    "screener_sigma_col_roe": "ROE",
    "screener_sigma_col_zone": "Zone",
    "screener_sigma_col_psycho": "Psychologie",
    "screener_sigma_col_analyse": "📈 Analyser",
    "screener_sigma_col_wl": "⭐ WL",
    "screener_sigma_analyse_help": "Cochez pour lancer l'analyse de ce ticker",
    "screener_sigma_wl_help": "Ajouter/retirer de la watchlist",
    "screener_sigma_position": "Position :",
    "screener_sigma_zone_lbl": "Zone :",
    "screener_sigma_init": "Initialisation…",
    "screener_sigma_analyse_progress": "Analyse {ticker}…",
    "screener_sigma_click_to_start": "👆 Cliquez sur **🔍 Lancer le scan** pour démarrer l'analyse.",
    "screener_multi_desc": "Combinez critères **fondamentaux** et **position sigma** pour identifier les meilleures opportunités.",
    "screener_multi_scan_params": "🗂️ Paramètres de scan",
    "screener_multi_period_label": "Période d'analyse",
    "screener_multi_index_label": "Indice / Watchlist à scanner",
    "screener_multi_index_help": "Les entrées ⭐ correspondent à vos watchlists",
    "screener_multi_fund_filters": "📊 Filtres fondamentaux",
    "screener_multi_rev_min": "Croissance CA min (%)",
    "screener_multi_roic_min": "ROIC min (%)",
    "screener_multi_fcfm_min": "Marge FCF min (%)",
    "screener_multi_debt_max": "Dette/FCF max",
    "screener_multi_score_min": "Score global min (/10)",
    "screener_multi_sigma_filters": "🔭 Filtres sigma",
    "screener_multi_sigma_filters_note": "(cochez les zones acceptées)",
    "screener_multi_reset_help": "Remet tous les curseurs à leurs valeurs par défaut",
    "screener_multi_found": "✅ **{n} action(s)** correspondent à vos critères  •  {index}  •  {period}  •  *{total} données chargées — filtrage en temps réel*",
    "screener_multi_col_ticker": "Ticker",
    "screener_multi_col_company": "Société",
    "screener_multi_col_score": "Score",
    "screener_multi_col_sigma": "Position σ",
    "screener_multi_col_zone": "Zone",
    "screener_multi_col_rev": "Croiss. CA",
    "screener_multi_col_roic": "ROIC",
    "screener_multi_col_roe": "ROE",
    "screener_multi_col_fcfm": "Marge FCF",
    "screener_multi_col_debt": "Dette/FCF",
    "screener_multi_col_pe": "P/E",
    "screener_multi_col_peg": "PEG",
    "screener_multi_col_analyse": "📈 Analyser",
    "screener_multi_col_wl": "⭐ WL",
    "screener_multi_analyse_help": "Cochez pour lancer l'analyse de ce ticker",
    "screener_multi_wl_help": "Ajouter/retirer de la watchlist",
    "screener_multi_charts_title": "📈 Graphiques — {n} action(s) sélectionnée(s)",
    "screener_multi_configure_first": "👆 Configurez les filtres puis cliquez sur **🚀 Lancer le screener**.",
    "screener_multi_score_lbl": "Score :",
    "screener_multi_init": "Initialisation…",
    "screener_multi_progress": "Analyse {ticker}…",
    "chart_yaxis_help_short": "Linéaire ou logarithmique",
    "chart_display_help_short": "Cours brut ou variation en % — Variation % indisponible en échelle logarithmique",
    "chart_display_help_scr": "Cours brut ou variation en %",
    "comp_ticker_manual_label": "Ajouter un ticker manuellement",
    "comp_ticker_ph": "ex : AAPL, MC.PA, ^GSPC…",
    "comp_period_label": "Horizon temporel",
    "comp_add_from_index": "Ajouter depuis les indices / watchlists chargés",
    "comp_add_from_index_help": "Les entrées ⭐ correspondent à vos watchlists",
    "comp_launch_btn": "📊 Comparer",
    "comp_load_spinner": "Chargement des données de marché…",
    "comp_best": "🥇 Meilleure valeur",
    "comp_worst": "📉 Moins bonne valeur",
    "comp_norm_price": "Prix normalisé (base 1)",
    "comp_date_axis": "Date",
    "comp_col_ticker": "Ticker",
    "comp_col_name": "Nom",
    "comp_col_perf": "Performance",
    "comp_col_vol": "Volatilité ann.",
    "comp_col_drawdown": "Max Drawdown",
    "comp_col_analyse": "📈 Analyser",
    "comp_col_wl": "⭐ Watchlist",
    "comp_analyse_help": "Lancer l'analyse individuelle",
    "comp_wl_help": "Ajouter/retirer de la watchlist",
    "comp_errors": "Données introuvables pour : {tickers}",
    "explain_subtitle": "Comprendre chaque métrique utilisée dans les scorecards et le screener.",
    "scorecard_global_score": "**Score global** basé sur 7 critères fondamentaux :",
    "score_grade_A": "Excellente qualité",
    "score_grade_B": "Bonne qualité",
    "score_grade_C": "Qualité moyenne",
    "score_grade_D": "Qualité faible",
    "score_grade_F": "Qualité insuffisante",
    "hist_growth_expander": "📈 Historique Indicateurs de Croissance",
    "hist_profit_expander": "💰 Historique Indicateurs de Rentabilité",
    "hist_valuation_expander": "⚖️ Historique Indicateurs de Valorisation",
    "hist_solidity_expander": "🏦 Historique Indicateurs de Solidité Financière",
    "hist_synthesis_title": "📋 Synthèse CA→FCF→Marge ({year})",
    "hist_no_synthesis": "Données synthèse insuffisantes.",
    "company_sector": "Secteur",
    "company_industry": "Industrie",
    "company_country": "Pays",
    "company_employees": "Employés",
    "company_website": "Site web",
    "company_description": "Description",
    "pp_positions_count": "📊 **{n} position(s)** dans **{name}** :",
    "pp_more_positions": "… et {n} autre(s) position(s) non affichée(s).",
    "pp_import_count": "📥 **{n} position(s)** seront importées depuis **{name}** avec : Ticker, Nom, PRU en EUR.",
    "config_wiki_select_index": "Indice à mettre à jour",
    "sigma_position_label": "📍 Position actuelle :",

}
