# ============================================================
# SIGMASCOPE — Translation dictionary ENGLISH
# ============================================================

TRANSLATIONS = {

    # ── Language ─────────────────────────────────────────────
    "lang_selector_label": "🌐 Langue / Language / Dil",
    "lang_fr": "🇫🇷 Français",
    "lang_en": "🇬🇧 English",
    "lang_tr": "🇹🇷 Türkçe",

    # ── Sidebar ──────────────────────────────────────────────
    "sidebar_title":        "🚀 SigmaScope by jp",
    "sidebar_nav":          "### 🗂️ Navigation",
    "sidebar_indices":      "**📂 Loaded indices**",
    "sidebar_no_index":     "⚠️ No index loaded.\nGo to ⚙️ Configuration.",
    "sidebar_valeurs":      "values",
    "sidebar_stop":         "⏹️ Stop application",
    "sidebar_stop_help":    "Stop the Streamlit server",
    "sidebar_stopping":     "Stopping…",

    # ── Pages navigation ─────────────────────────────────────
    "page_presentation":    "🏠 Overview",
    "page_analyse":         "📈 Stock analysis",
    "page_watchlists":      "⭐ Watchlists",
    "page_comparaison":     "🔀 Peer comparison",
    "page_screener_sigma":  "🔭 Sigma Screener",
    "page_screener_multi":  "🎛️ Multi-criteria screener",
    "page_explications":    "📖 Documentation",
    "page_configuration":   "⚙️ Configuration",

    # ── Page Overview — Hero ─────────────────────────────────
    "hero_tagline":         "The all-in-one quantitative stock analysis platform",
    "hero_tagline2":        "Log regression · Fundamental analysis · Screener · DCF valuation",
    "hero_version":         "✨ Version 24 — by jp",
    "hero_pp_compat":       "🤝 Compatible with",
    "hero_pp_desc":         "— direct import of your portfolio (XML file)",

    # ── Page Overview — Features ─────────────────────────────
    "feat_title":           "### 🧩 Main features",
    "feat_open_analyse":    "→ Open Stock analysis",
    "feat_open_watchlist":  "→ Open Watchlists",
    "feat_open_comparaison":"→ Open Peer comparison",
    "feat_open_screener_s": "→ Open Sigma Screener",
    "feat_open_screener_m": "→ Open Multi-criteria screener",
    "feat_open_valorisation":"→ See in Stock analysis",

    # ── Page Overview — Stats badges ─────────────────────────
    "stat_modules":         "Analysis modules",
    "stat_indices":         "Loaded indices",
    "stat_tickers":         "Pre-loaded tickers (∞ via Yahoo Finance)",
    "stat_methods":         "Valuation methods",
    "stat_sigma_zones":     "Sigma zones detected",

    # ── Page Overview — Quick start ──────────────────────────
    "quickstart_title":     "### 🚀 Quick start",
    "sigma_zones_title":    "### 📐 Understanding sigma zones",

    # ── Page Overview — Roadmap ──────────────────────────────
    "roadmap_expander":     "🛠️ Roadmap & upcoming features",
    "roadmap_title":        "#### 🚧 In development / coming soon",
    "roadmap_legend_high":  "🔴 High priority",
    "roadmap_legend_study": "🟢 Under consideration",
    "roadmap_caption":      "💡 Tell me what would be most useful to you in the **Suggestions** section below!",
    "roadmap_item1_title":  "Fair value calculation review",
    "roadmap_item1_desc":   "In-depth review of **DCF, Gordon-Shapiro, Multiples and NAV** methods — verifying formula consistency, default assumptions and results against financial valuation standards.",
    "roadmap_item2_title":  "Google authentication",
    "roadmap_item2_desc":   "Replace the anonymous token with a **real Google account** — to access your watchlists from any device. Leave me a comment if this matters to you 👇",
    "roadmap_item3_title":  "Data export",
    "roadmap_item3_desc":   "Export watchlists and analysis results to **CSV / Excel**. Leave me a comment if you need this 👇",
    "roadmap_item4_title":  "Advanced screener",
    "roadmap_item4_desc":   "Add technical filters (RSI, Bollinger) to the multi-criteria screener. Leave me a comment if this would be useful 👇",
    "roadmap_item5_title":  "Yahoo Finance stability",
    "roadmap_item5_desc":   "Yahoo Finance rate limiting can cause intermittent errors. An official replacement API is under consideration. Leave me a comment if you often face this issue 👇",
    "roadmap_item6_title":  "Migration to a full website",
    "roadmap_item6_desc":   "If usage justifies it, a migration to a **full web application** (FastAPI + React) is being considered. Vote below and leave a comment 👇",

    # ── Page Overview — Stats & ratings ──────────────────────
    "stats_expander":           "📊 Usage statistics",
    "stats_users":              "Unique users",
    "stats_sessions":           "Total sessions",
    "stats_duration":           "Avg. session duration",
    "stats_rating":             "reviews",
    "stats_saas_vote":          "Website migration vote",
    "stats_rating_title":       "#### ⭐ Rate this app",
    "stats_your_note":          "Your rating",
    "stats_saas_question":      "Should SigmaScope be converted to a full website?",
    "stats_saas_yes":           "✅ Yes, convert to a full website",
    "stats_saas_no":            "❌ No, the Streamlit app is fine",
    "stats_save_btn":           "💾 Save my review",
    "stats_save_ok":            "✅ Thank you! Rating: {stars} — SaaS vote: {vote}",
    "stats_save_oui":           "Yes",
    "stats_save_non":           "No",
    "stats_save_err":           "❌ Error while saving.",

    # ── Page Overview — Suggestions ──────────────────────────
    "feedback_expander":        "💬 Suggestions & improvements",
    "feedback_title":           "#### 📝 Leave a message",
    "feedback_visibility":      "Message visibility",
    "feedback_public":          "🌐 Public — visible to everyone",
    "feedback_private":         "🔒 Private — visible to administrator only",
    "feedback_caption_private": "🔒 This message will only be visible to the administrator.",
    "feedback_caption_public":  "🌐 This message will be visible to all users.",
    "feedback_placeholder":     "E.g.: Add a MACD indicator, improve the screener page...",
    "feedback_send_btn":        "📤 Send",
    "feedback_ok_private":      "✅ Private message sent to the administrator, thank you!",
    "feedback_ok_public":       "✅ Public message sent, thank you!",
    "feedback_err":             "❌ Error while sending.",
    "feedback_empty":           "⚠️ Message cannot be empty.",
    "feedback_community_title": "#### 💡 Community suggestions",
    "feedback_none":            "No suggestions yet — be the first!",

    # ── Footer ───────────────────────────────────────────────
    "footer_text":  "⚡ SigmaScope uses <strong style=\"color:#4C9BE8;\">Yahoo Finance</strong> as data source · Designed for quantitative analysis · <em>Not investment advice</em>",

    # ── Stock analysis page ───────────────────────────────────
    "analyse_title":            "📈 Stock analysis",
    "analyse_params_expander":  "🔍 Analysis parameters",
    "analyse_ticker_label":     "Ticker / Company",
    "analyse_ticker_help":      "Filtering search across all loaded indices",
    "analyse_ticker_placeholder":"Type a ticker (AAPL) or company name (Apple)…",
    "analyse_ticker_manual":    "Manual ticker",
    "analyse_ticker_manual_ph": "e.g.: AAPL, BNP.PA…",
    "analyse_indice_label":     "Choose an index / watchlist",
    "analyse_composant_label":  "Component ({n} values)",
    "analyse_no_index":         "⚠️ No data. Go to ⚙️ Configuration.",
    "analyse_choose_index":     "— choose an index first —",
    "analyse_period_label":     "Period",
    "analyse_ticker_selected":  "Selected ticker:",
    "analyse_launch_btn":       "🚀 Run Analysis",
    "analyse_loading":          "Loading data…",
    "analyse_no_data":          "No data available for this ticker.",
    "analyse_error":            "Error: {e}",
    "analyse_configure_first":  "👆 Configure a ticker above then click **🚀 Run Analysis**.",

    # ── Analysis — sub-sections ───────────────────────────────
    "analyse_tech_expander":    "📊 Technical Analysis",
    "analyse_fair_expander":    "💰 Historical Fair Value",
    "analyse_score_expander":   "📊 Fundamental Scorecard & Global Score",
    "analyse_histo_expander":   "📊 Historical Fundamental Indicators",
    "analyse_info_expander":    "🏢 Company information",
    "analyse_trend_expander":   "📈 Trend Analysis",
    "analyse_adv_params":       "⚙️ Advanced parameters",

    # ── Analysis — Technical ─────────────────────────────────
    "tc_period_warning":        "⚠️ Period limited to **{period}** for granularity {interval}.",
    "tc_no_data":               "No data available for this ticker.",
    "tc_chart_err":             "Error loading technical chart: {e}",

    # ── Analysis — Fair Value ─────────────────────────────────
    "fv_no_data":               "ℹ️ Insufficient data to compute fair value with this method ({method}).",
    "fv_no_fetch":              "⚠️ Unable to retrieve data to compute fair value.",

    # ── Watchlists ────────────────────────────────────────────
    "wl_title":                 "⭐ My Watchlists",
    "wl_info":                  "🔑 **Your watchlists are saved** in a secure database, identified by a unique anonymous token linked to your browser (token: `{uid}`).  \n📌 **Bookmark this page** to access your watchlists anytime — the URL contains your token.  \n⚠️ **Expiry**: if you don't return for **30 days**, your watchlists will be automatically deleted from the database.",
    "wl_manage_expander":       "🗂️ Watchlist management",
    "wl_active_label":          "📋 Active watchlist",
    "wl_new_btn":               "➕ New",
    "wl_delete_btn":            "🗑️ Delete",
    "wl_delete_help":           "Delete watchlist '{name}'",
    "wl_import_btn":            "📥 Import",
    "wl_import_help":           "Import a portfolio from Portfolio Performance (.xml)",
    "wl_delete_confirm_msg":    "⚠️ Delete watchlist **{name}** and all its entries?",
    "wl_delete_confirm_btn":    "🗑️ Confirm deletion",
    "wl_delete_cancel_btn":     "❌ Cancel",
    "wl_autosave":              "💾 **{name}** — auto-saved",
    "wl_add_expander":          "➕ Add a stock manually",
    "wl_add_ticker_label":      "Ticker",
    "wl_add_ticker_ph":         "e.g.: AAPL, BNP.PA",
    "wl_add_btn":               "➕ Add",
    "wl_add_ok":                "✅ {ticker} added to watchlist!",
    "wl_add_duplicate":         "{ticker} is already in the watchlist.",
    "wl_add_empty":             "Enter a ticker.",
    "wl_empty_info":            "👆 Your watchlist is empty. Add stocks using the **⭐ Watchlist** button on any page, or manually above.",
    "wl_refresh_btn":           "🔄 Refresh data",
    "wl_data_errors":           "⚠️ Data unavailable for: {tickers}",
    "wl_analyse_tip":           "💡 Check **📈** on the left to launch individual stock analysis",
    "wl_sigma_expander":        "📈 Watchlist chart (sigma positions)",
    "wl_pru_expander":          "💰 Watchlist chart (price vs average cost)",
    "wl_manage2_expander":      "⚙️ Watchlist management",
    "wl_remove_tip":            "💡 Check **🗑️ Remove** to delete a stock from the watchlist",
    "wl_edit_expander":         "✏️ Add a note / purchase price",
    "wl_save_edit_btn":         "💾 Save",
    "wl_edit_ok":               "✅ Updated.",
    "wl_sigma_no_data":         "Sigma data unavailable.",
    "wl_pru_no_data":           "No purchase price entered in this watchlist.",

    # ── Peer comparison ───────────────────────────────────────
    "comp_title":               "🔀 Peer comparison",
    "comp_params_expander":     "🔍 Comparison parameters",
    "comp_selected":            "**Selected stocks:** {tickers}",
    "comp_no_data":             "No data available.",
    "comp_table_title":         "📋 Performance table",
    "comp_tip":                 "💡 Check **📈 Analyse** for individual analysis · Check **⭐ Watchlist** to add/remove",
    "comp_configure_first":     "👆 Select stocks then click **📊 Compare**.",

    # ── Sigma Screener ────────────────────────────────────────
    "screener_sigma_title":     "🔭 Sigma Screener — Scan index stocks",
    "screener_sigma_params":    "🔍 Scan parameters",
    "screener_sigma_no_index":  "⚠️ No index loaded. Go to ⚙️ Configuration.",
    "screener_sigma_launch":    "🔍 Run scan",
    "screener_sigma_scanning":  "🔄 Scanning **{n}** stocks from **{index}** over **{period}** — zones: **{zones}**",
    "screener_sigma_errors":    "⚠️ Unavailable data: {tickers}",
    "screener_sigma_no_result": "No stocks found for the selected zones.",
    "screener_sigma_found":     "✅ **{n} stock(s) found**  •  {index}  •  {period}",
    "screener_sigma_tip":       "💡 Check **📈 Analyse** to launch analysis · Check **⭐ WL** to add/remove from watchlist",
    "screener_sigma_charts":    "📈 Charts — {n} stock(s)",
    "screener_sigma_log_warn":  "⚠️ % variation incompatible with log scale",
    "screener_sigma_select_zone":"👆 Select at least one zone then click **🔍 Run scan**.",

    # ── Multi-criteria screener ───────────────────────────────
    "screener_multi_title":     "🎛️ Multi-criteria screener",
    "screener_multi_params":    "🔍 Screener parameters",
    "screener_multi_no_index":  "⚠️ No index loaded. Go to ⚙️ Configuration.",
    "screener_multi_launch":    "🚀 Run screener",
    "screener_multi_reset":     "↺ Reset filters",
    "screener_multi_no_sigma":  "ℹ️ No sigma zone selected = all zones accepted.",
    "screener_multi_scanning":  "🔄 Scanning **{n}** stocks from **{index}** — loading data…",
    "screener_multi_errors":    "⚠️ Errors on: {tickers}",

    # ── Documentation page ────────────────────────────────────
    "explain_title":            "📖 Indicators & valuation methods guide",
    "explain_scoring_title":    "### 📊 Scoring Indicators",
    "explain_valuation_title":  "### 💰 Valuation: How to compute the Fair Value of a Stock?",
    "explain_params_title":     "### ⚙️ Valuation Parameters Guide",
    "explain_sensitivity_cap":  "💡 Items marked **increases strongly** are the most sensitive parameters — test them in pessimistic/optimistic scenarios before any investment decision.",

    # ── Configuration page ────────────────────────────────────
    "config_title":             "⚙️ Configuration — Index management",
    "config_indices_title":     "📊 Loaded indices status",
    "config_preview_title":     "🔍 Component preview",
    "config_preview_select":    "Show components for",
    "config_choose_index":      "-- Choose an index --",
    "config_no_index":          "ℹ️ No index loaded. Log in as administrator to update.",
    "config_admin_title":       "🔐 Administration",
    "config_admin_caption":     "This section is restricted to the administrator.",
    "config_admin_pwd_ph":      "••••••••",
    "config_admin_login_btn":   "🔑 Access",
    "config_admin_err":         "❌ Incorrect password.",
    "config_admin_ok":          "✅ Administrator mode enabled",
    "config_admin_logout":      "🔓 Logout",
    "config_wiki_expander":     "🔄 Update Wikipedia indices",
    "config_wiki_desc":         "Reload stock index components from Wikipedia.",
    "config_wiki_select":       "Index to update",
    "config_wiki_none":         "-- None --",
    "config_wiki_btn":          "🔄 Update",
    "config_wiki_btn_help":     "Reload this index from Wikipedia",
    "config_wiki_source":       "🌐 Source:",
    "config_wiki_ok":           "✅ {n} components saved for {label}.",
    "config_wiki_err":          "Scraping error: {e}",
    "config_wiki_select_first": "Please select an index first.",
    "config_wiki_loading":      "Loading {label}…",
    "config_sys_expander":      "ℹ️ System information",
    "config_cache_btn":         "🧹 Purge market cache (> 2h)",
    "config_cache_ok":          "✅ Cache purged.",
    "config_private_expander":  "🔒 Private user messages",
    "config_private_none":      "No private messages yet.",
    "config_purge_expander":    "🗑️ Inactive watchlist cleanup",
    "config_purge_caption":     "Deletes watchlists (and their contents) from users who have not logged in for more than 30 days. ⚠️ Irreversible operation.",
    "config_purge_btn":         "🗑️ Purge inactive watchlists (> 30d)",
    "config_purge_ok":          "✅ {n} inactive watchlist(s) deleted.",
    "config_purge_none":        "ℹ️ No inactive watchlists to delete.",

    # ── Portfolio Performance import ──────────────────────────
    "pp_dialog_title":          "📥 Import from Portfolio Performance",
    "pp_step1":                 "📂 Loading",
    "pp_step2":                 "🏦 Account",
    "pp_step3":                 "✅ Confirmation",
    "pp_upload_label":          "**Load the Portfolio Performance XML file**",
    "pp_upload_caption":        "Menu *File → Save as…* in Portfolio Performance.",
    "pp_upload_info":           "👆 Select your Portfolio Performance file (.xml) above.",
    "pp_upload_close":          "❌ Close",
    "pp_upload_err":            "❌ Parse error: {e}",
    "pp_select_label":          "**Choose the account to import**",
    "pp_select_account":        "Account",
    "pp_select_pru_note":       "ℹ️ Average costs are in EUR (Portfolio Performance currency) and will be imported as-is.",
    "pp_next_btn":              "▶️ Next",
    "pp_back_btn":              "◀️ Back",
    "pp_cancel_btn":            "❌ Cancel",
    "pp_confirm_label":         "**Name the watchlist and confirm import**",
    "pp_wl_name_label":         "Watchlist name",
    "pp_wl_name_help":          "A new watchlist will be created with this name (or replaced if it already exists).",
    "pp_wl_exists":             "⚠️ Watchlist **{name}** already exists — its content will be **replaced**.",
    "pp_wl_new":                "✨ A new watchlist **{name}** will be created.",
    "pp_import_btn":            "📥 Import",
    "pp_import_empty_name":     "Name cannot be empty.",
    "pp_import_ok":             "✅ {n} position(s) imported into **{name}**!",

    # ── Watchlist dialog ──────────────────────────────────────
    "wl_dialog_title":          "🗂️ Which watchlist to add this ticker to?",
    "wl_dialog_add_label":      "**Add `{ticker}`** ({company}) to watchlist:",
    "wl_dialog_target":         "Target watchlist",
    "wl_dialog_already":        "⚠️ `{ticker}` is already in **{name}**.",
    "wl_dialog_add_btn":        "✅ Add",
    "wl_dialog_cancel_btn":     "❌ Cancel",
    "wl_dialog_add_ok":         "⭐ {ticker} added to **{name}**!",
    "wl_dialog_remove_msg":     "**Remove `{ticker}`** from watchlist **{name}**?",
    "wl_dialog_remove_btn":     "🗑️ Remove",
    "wl_dialog_remove_ok":      "❌ {ticker} removed from watchlist",
    "wl_btn_add":               "⭐ Watchlist",
    "wl_btn_in":                "✅ Watchlist",
    "wl_btn_add_help":          "Add to watchlist ({name})",
    "wl_btn_remove_help":       "Remove from watchlist ({name})",

    # ── Supabase / connection ─────────────────────────────────
    "supabase_err":             "❌ Cannot connect to Supabase: {e}",

    # ── General ───────────────────────────────────────────────
    "min_suffix":               "min",
    "values_suffix":            "values",
    "loading":                  "Loading…",
    "error_prefix":             "Error: ",
    "analyse_launch_btn": "🚀 Run Analysis",
    "analyse_period_default": "10 Years",
    "analyse_data_not_found": "Data not found for this ticker.",
    "analyse_loading_fundamentals": "Loading fundamental data…",
    "analyse_ticker_selected_html": "Selected ticker:",
    "analyse_yahoo_link": "View on Yahoo Finance →",
    "analyse_position_sigma": "📍 Current position:",
    "chart_period_label": "Period",
    "chart_yaxis_label": "Y Scale",
    "chart_yaxis_linear": "Linear",
    "chart_yaxis_log": "Logarithmic",
    "chart_yaxis_help": "Linear: absolute values  |  Logarithmic: better for long periods",
    "chart_display_label": "Y Display",
    "chart_display_cours": "Price",
    "chart_display_pct": "% Change",
    "chart_display_help": "Price: raw price  |  % Change: performance since start of period",
    "chart_display_log_disabled": "  ⚠️ Disabled in logarithmic scale",
    "chart_cours_title": "Price",
    "tc_period_section": "**Period**",
    "tc_granularity_section": "**Granularity**",
    "tc_indicators_section": "**Indicators**",
    "tc_ma_label": "Moving averages",
    "tc_bb_label": "Bollinger",
    "tc_rsi_label": "RSI",
    "tc_volume_label": "Volume",
    "tc_ma_periods_section": "**MA Periods**",
    "tc_bb_period_label": "BB Period",
    "tc_bb_std_label": "BB Std dev",
    "tc_options_section": "**Options**",
    "tc_hide_gaps_label": "Hide gaps",
    "tc_hide_gaps_help": "Removes gaps on the X axis for periods when the market is closed (nights, weekends, holidays)",
    "fv_method_label": "Valuation method",
    "fv_granularity_label": "Granularity",
    "fv_gran_monthly": "Monthly",
    "fv_gran_weekly": "Weekly",
    "fv_gran_yearly": "Yearly",
    "fv_overlay_label": "Overlay actual price",
    "fv_auto_label": "Auto method",
    "fv_auto_help": "Automatically selects: {method}",
    "fv_suggested": "Suggested method:",
    "fv_adv_params_caption": "Greyed-out parameters do not apply to the selected method. Default values are automatically estimated from beta, debt and sector.",
    "fv_wacc_label": "WACC k (%)",
    "fv_g_label": "Perpetual growth g (%)",
    "fv_k_gs_label": "Required return Gordon (%)",
    "fv_horizon_label": "DCF horizon (years)",
    "fv_calc_spinner": "Computing fair value…",
    "fv_dcf_only": "⚠️ DCF only",
    "fv_gordon_only": "⚠️ Gordon-Shapiro only",
    "fv_gap_overvalued": "Overvalued by {pct:.1f}%",
    "fv_gap_undervalued": "Undervalued by {pct:.1f}%",
    "wl_create_name_label": "New watchlist name",
    "wl_create_btn": "✅ Create",
    "wl_create_cancel": "Cancel",
    "wl_name_empty_err": "Name cannot be empty.",
    "wl_name_exists_err": "This name already exists.",
    "wl_created_ok": "✅ Watchlist **{name}** created!",
    "wl_deleted_ok": "✅ Watchlist deleted.",
    "wl_loading_data": "Loading data…",
    "wl_loading_ticker": "Loading {ticker}…",
    "wl_col_ticker": "Ticker",
    "wl_col_company": "Company",
    "wl_col_date": "Added",
    "wl_col_note": "Note",
    "wl_col_pru": "Avg cost (€)",
    "wl_col_price": "Price (€)",
    "wl_col_change": "Day chg. (%)",
    "wl_col_sigma": "σ Position",
    "wl_col_score": "Score",
    "wl_col_roic": "ROIC (%)",
    "wl_col_revenue": "Rev. growth (%)",
    "wl_col_fcfm": "FCF margin (%)",
    "wl_col_debt": "Debt/FCF",
    "wl_col_peg": "PEG",
    "wl_col_pru_pct": "Avg cost gap (%)",
    "wl_col_remove": "🗑️ Remove",
    "wl_note_placeholder": "Free note…",
    "wl_pru_placeholder": "Purchase price…",
    "wl_edit_ok": "✅ Updated.",
    "wl_sigma_chart_title": "Sigma position — {period}",
    "wl_pru_chart_title": "Current price (€) vs average cost (€)",
    "wl_progress_init": "Loading data…",
    "wl_ticker_manual_label": "Add a ticker manually",
    "wl_ticker_ph": "e.g.: AAPL, MC.PA, ^GSPC…",
    "wl_period_select": "Time horizon",
    "wl_add_from_index": "Add from loaded indices / watchlists",
    "wl_add_from_index_help": "Lines '── Select all: … ──' add all stocks. ⭐ entries are your watchlists.",
    "wl_compare_btn": "📊 Compare",
    "wl_load_market_data": "Loading market data…",
    "wl_best_stock": "🥇 Best performer",
    "wl_worst_stock": "📉 Worst performer",
    "wl_col_name": "Name",
    "wl_col_perf": "Performance",
    "wl_col_vol": "Ann. volatility",
    "wl_col_drawdown": "Max Drawdown",
    "wl_col_analyse": "📈 Analyse",
    "wl_norm_price": "Normalised price (base 1)",
    "wl_no_data_comp": "Data not found for: {tickers}",
    "screener_sigma_period_label": "📅 Analysis period",
    "screener_sigma_index_label": "📂 Index / Watchlist to scan",
    "screener_sigma_index_help": "⭐ entries correspond to your watchlists",
    "screener_sigma_zones_title": "**🎯 Zones to search** *(check one or more zones)*",
    "screener_sigma_col_ticker": "Ticker",
    "screener_sigma_col_company": "Company",
    "screener_sigma_col_sigma": "σ Position",
    "screener_sigma_col_roe": "ROE",
    "screener_sigma_col_zone": "Zone",
    "screener_sigma_col_psycho": "Psychology",
    "screener_sigma_col_analyse": "📈 Analyse",
    "screener_sigma_col_wl": "⭐ WL",
    "screener_sigma_analyse_help": "Check to launch analysis for this ticker",
    "screener_sigma_wl_help": "Add/remove from watchlist",
    "screener_sigma_position": "Position:",
    "screener_sigma_zone_lbl": "Zone:",
    "screener_sigma_init": "Initialising…",
    "screener_sigma_analyse_progress": "Analysing {ticker}…",
    "screener_sigma_click_to_start": "👆 Click **🔍 Run scan** to start the analysis.",
    "screener_multi_desc": "Combine **fundamental** criteria and **sigma position** to identify the best opportunities.",
    "screener_multi_scan_params": "🗂️ Scan parameters",
    "screener_multi_period_label": "Analysis period",
    "screener_multi_index_label": "Index / Watchlist to scan",
    "screener_multi_index_help": "⭐ entries correspond to your watchlists",
    "screener_multi_fund_filters": "📊 Fundamental filters",
    "screener_multi_rev_min": "Min revenue growth (%)",
    "screener_multi_roic_min": "Min ROIC (%)",
    "screener_multi_fcfm_min": "Min FCF margin (%)",
    "screener_multi_debt_max": "Max Debt/FCF",
    "screener_multi_score_min": "Min global score (/10)",
    "screener_multi_sigma_filters": "🔭 Sigma filters",
    "screener_multi_sigma_filters_note": "(check accepted zones)",
    "screener_multi_reset_help": "Reset all sliders to default values",
    "screener_multi_found": "✅ **{n} stock(s)** match your criteria  •  {index}  •  {period}  •  *{total} loaded — real-time filtering*",
    "screener_multi_col_ticker": "Ticker",
    "screener_multi_col_company": "Company",
    "screener_multi_col_score": "Score",
    "screener_multi_col_sigma": "σ Position",
    "screener_multi_col_zone": "Zone",
    "screener_multi_col_rev": "Rev. growth",
    "screener_multi_col_roic": "ROIC",
    "screener_multi_col_roe": "ROE",
    "screener_multi_col_fcfm": "FCF margin",
    "screener_multi_col_debt": "Debt/FCF",
    "screener_multi_col_pe": "P/E",
    "screener_multi_col_peg": "PEG",
    "screener_multi_col_analyse": "📈 Analyse",
    "screener_multi_col_wl": "⭐ WL",
    "screener_multi_analyse_help": "Check to launch analysis for this ticker",
    "screener_multi_wl_help": "Add/remove from watchlist",
    "screener_multi_charts_title": "📈 Charts — {n} selected stock(s)",
    "screener_multi_configure_first": "👆 Configure filters then click **🚀 Run screener**.",
    "screener_multi_score_lbl": "Score:",
    "screener_multi_init": "Initialising…",
    "screener_multi_progress": "Analysing {ticker}…",
    "chart_yaxis_help_short": "Linear or logarithmic",
    "chart_display_help_short": "Raw price or % change — % change unavailable in logarithmic scale",
    "chart_display_help_scr": "Raw price or % change",
    "comp_ticker_manual_label": "Add a ticker manually",
    "comp_ticker_ph": "e.g.: AAPL, MC.PA, ^GSPC…",
    "comp_period_label": "Time horizon",
    "comp_add_from_index": "Add from loaded indices / watchlists",
    "comp_add_from_index_help": "⭐ entries correspond to your watchlists",
    "comp_launch_btn": "📊 Compare",
    "comp_load_spinner": "Loading market data…",
    "comp_best": "🥇 Best performer",
    "comp_worst": "📉 Worst performer",
    "comp_norm_price": "Normalised price (base 1)",
    "comp_date_axis": "Date",
    "comp_col_ticker": "Ticker",
    "comp_col_name": "Name",
    "comp_col_perf": "Performance",
    "comp_col_vol": "Ann. volatility",
    "comp_col_drawdown": "Max Drawdown",
    "comp_col_analyse": "📈 Analyse",
    "comp_col_wl": "⭐ Watchlist",
    "comp_analyse_help": "Launch individual analysis",
    "comp_wl_help": "Add/remove from watchlist",
    "comp_errors": "Data not found for: {tickers}",
    "explain_subtitle": "Understand each metric used in scorecards and the screener.",
    "scorecard_global_score": "**Global score** based on 7 fundamental criteria:",
    "score_grade_A": "Excellent quality",
    "score_grade_B": "Good quality",
    "score_grade_C": "Average quality",
    "score_grade_D": "Poor quality",
    "score_grade_F": "Insufficient quality",
    "hist_growth_expander": "📈 Historical Growth Indicators",
    "hist_profit_expander": "💰 Historical Profitability Indicators",
    "hist_valuation_expander": "⚖️ Historical Valuation Indicators",
    "hist_solidity_expander": "🏦 Historical Financial Strength Indicators",
    "hist_synthesis_title": "📋 Revenue→FCF→Margin Summary ({year})",
    "hist_no_synthesis": "Insufficient synthesis data.",
    "company_sector": "Sector",
    "company_industry": "Industry",
    "company_country": "Country",
    "company_employees": "Employees",
    "company_website": "Website",
    "company_description": "Description",
    "pp_positions_count": "📊 **{n} position(s)** in **{name}**:",
    "pp_more_positions": "… and {n} more position(s) not shown.",
    "pp_import_count": "📥 **{n} position(s)** will be imported from **{name}** with: Ticker, Name, avg cost in EUR.",
    "config_wiki_select_index": "Index to update",
    "sigma_position_label": "📍 Current position:",

    'guide_growth_title': '📈 Growth Indicators',
    'guide_profit_title': '💰 Profitability Indicators',
    'guide_valuation_title': '⚖️ Valuation Indicators',
    'guide_solidity_title': '🏦 Financial Strength Indicators',
    'guide_sigma_title': '📐 Sigma Indicators (Regression Position)',
    'guide_rev_name': 'Revenue Growth (CAGR)',
    'guide_rev_body': 'Measures average annual revenue growth. Strong revenue growth indicates a company gaining market share. Warning: high revenue growth without profitability may signal a cash-burning company.',
    'guide_rev_target': '> 10% per year',
    'guide_rev_interp': '< 0%: decline | 0-5%: weak | 5-10%: fair | > 10%: strong | > 20%: exceptional',
    'guide_fcf_name': 'Free Cash Flow Growth (CAGR)',
    'guide_fcf_body': 'FCF growth is often more meaningful than revenue growth since FCF is cash actually generated after investments. A company where FCF grows faster than revenue is improving its margins. Favourite metric of value investors.',
    'guide_fcf_target': '> 10% per year',
    'guide_fcf_interp': 'Ideally: FCF growth > revenue growth (margin improvement)',
    'guide_roic_name': 'ROIC — Return On Invested Capital',
    'guide_roic_body': 'Measures how efficiently a company uses capital to generate profits. A consistently high ROIC (> 15%) indicates a strong competitive advantage (moat). Warren Buffett considers ROIC one of the most important quality indicators.',
    'guide_roic_target': '> 15%',
    'guide_roic_interp': '< 8%: weak | 8-15%: fair | 15-25%: strong | > 25%: exceptional (moat)',
    'guide_roe_name': 'ROE — Return On Equity',
    'guide_roe_body': 'Measures return on shareholders equity. High and stable ROE indicates a company capable of creating shareholder value. Interpret with caution if heavily leveraged, as ROE can be artificially inflated.',
    'guide_roe_target': '> 15%',
    'guide_roe_interp': '< 10%: weak | 10-15%: fair | 15-25%: strong | > 25%: exceptional | Negative: losses',
    'guide_fcfm_name': 'Free Cash Flow Margin',
    'guide_fcfm_body': 'Percentage of revenue that becomes available cash after capex. A high FCF margin indicates an asset-light company. Software companies often exceed 30%, heavy industrials stay below 5%.',
    'guide_fcfm_target': '> 10%',
    'guide_fcfm_interp': '< 5%: weak | 5-10%: fair | 10-20%: strong | > 20%: exceptional',
    'guide_pe_name': 'P/E Ratio — Price to Earnings',
    'guide_pe_body': 'How many years of earnings an investor pays for a share. P/E must always be interpreted in context: sector, historical, and relative to growth. A high P/E is not necessarily expensive for a high-growth company.',
    'guide_pe_target': 'Indicative — depends on sector',
    'guide_pe_interp': 'Tech: 20-40x normal | Banks: 8-12x | Utilities: 12-18x',
    'guide_peg_name': 'PEG Ratio — Price/Earnings to Growth',
    'guide_peg_body': 'Adjusts P/E for growth: a P/E of 30 with 30% growth gives PEG of 1, considered fair. Invented by Peter Lynch. PEG < 1 suggests an undervalued stock relative to its growth.',
    'guide_peg_target': '< 2 (ideal < 1)',
    'guide_peg_interp': '< 1: potentially undervalued | 1-2: fair value | > 2: expensive relative to growth',
    'guide_pb_name': 'Price / Book (P/B)',
    'guide_pb_body': 'Compares market value to book value of assets. A P/B < 1 means the market values the company below its net assets (possible opportunity or sign of difficulty).',
    'guide_pb_target': '< 5 (sector-dependent)',
    'guide_pb_interp': 'Banks: 0.5-1.5x | Tech: 5-20x possible | < 1: discount on assets',
    'guide_pfcf_name': 'Price / Free Cash Flow (P/FCF)',
    'guide_pfcf_body': 'Harder to manipulate than P/E since FCF is less sensitive to accounting rules. Indicates how much an investor pays per euro of cash actually generated.',
    'guide_pfcf_target': '< 25',
    'guide_pfcf_interp': '< 15: potentially cheap | 15-25: fair | > 25: expensive | > 40: very expensive',
    'guide_debt_name': 'Net Debt / FCF',
    'guide_debt_body': 'How many years to repay net debt using generated FCF. A ratio < 3 indicates a financially healthy company. Negative value means more cash than debt.',
    'guide_debt_target': '< 3 years',
    'guide_debt_interp': '< 0: positive net cash | 0-3: healthy | 3-5: caution | > 5: risky',
    'guide_sigma_name': 'Sigma position',
    'guide_sigma_body': 'Measures how far the current price deviates from its long-term logarithmic trend, in standard deviations. Helps identify whether a stock is statistically overbought or oversold.',
    'guide_sigma_target': 'Depends on strategy',
    'guide_sigma_interp': '> +1.75: high excess zone | +0.75 to +1.25: strong trend | neutral near 0 | < -1.75: low excess zone',
    'guide_score_name': 'Global Score (/10 — Grade A to F)',
    'guide_score_body': 'Synthetic score on 7 weighted criteria: Revenue growth (x2), FCF growth (x2), ROIC (x2), FCF margin (x1), Debt/FCF (x1), PEG (x1), P/B (x1). A >= 8.5 | B >= 7.0 | C >= 5.5 | D >= 4.0 | F < 4.0.',
    'guide_score_target': '>= 7/10 (grade B or better)',
    'guide_score_interp': 'High score + low sigma position = potential buying opportunity',
    'guide_strategy_title': '### 💡 Combined strategy: Score + Sigma',
    'guide_strategy_body': 'The most powerful approach combines fundamental quality (global score) with technical timing (sigma position):',
    'guide_strategy_screener': '> **The multi-criteria screener** automates this combination across an entire index.',
    'guide_target_lbl': '🎯 Target:',
    'explain_valuation_intro': 'There is no universal method. Each approach relies on different assumptions and suits a specific company type. Great investors combine them.',
    'explain_params_intro': 'How to calibrate key assumptions for each method and understand their sensitivity.',
    'dcf_expander': '1  DCF — Discounted Cash Flow',
    'dcf_title': 'The discounted cash flow approach',
    'dcf_concept': "A company's value today equals the sum of all future cash flows discounted to present value. One euro received in 10 years is worth less than one euro received today.",
    'dcf_variables': 'FCFt: Free Cash Flow at year t | k: Discount rate (WACC), typically 8-12% | TV: Terminal Value, 60-80% of total | n: Forecast horizon (5-10 years)',
    'dcf_usecase': 'Use case: Predictable revenues and stable growth — Air Liquide, Microsoft, TotalEnergies.',
    'dcf_warning': 'Sensitivity: a 1% change in k or g can change the value by 20-40%. Always build pessimistic, central and optimistic scenarios.',
    'dcf_target': 'Reference method for long-term investing',
    'multiples_expander': '2  Market Multiples — Comparative Approach',
    'multiples_title': 'Peer comparison valuation',
    'multiples_concept': 'A stock is worth what the market pays for comparable companies. Relative valuation — we look at whether the stock is cheap or expensive versus peers.',
    'multiples_details': 'P/E (Price/Earnings): most popular | EV/EBITDA: for different capital structures | P/S: useful for unprofitable startups | P/FCF: preferred by value investors',
    'multiples_usecase': 'Use case: Homogeneous sectors — Banks, Automotive, Retail, Telecoms.',
    'multiples_warning': 'Limitation: if the entire sector is overvalued, the compared stock will be too. Says relatively cheap, not genuinely cheap.',
    'multiples_target': 'Quick method for screening and sector comparison',
    'gordon_expander': '3  Gordon-Shapiro — DDM (Dividend Discount Model)',
    'gordon_title': 'The Dividend Discount Model (DDM)',
    'gordon_concept': 'The stock is treated as a perpetual annuity. Its value is the discounted sum of all future dividends. Applies only to companies paying regular and predictable dividends.',
    'gordon_variables': 'D1: Expected dividend next year = D0 x (1+g) | k: Required rate of return | g: Perpetual annual dividend growth | Example: D1=2€, k=8%, g=3% → P=40€',
    'gordon_usecase': "Use case: Mature dividend-growing companies — Coca-Cola, L'Oreal, Orange, LVMH.",
    'gordon_warning': 'Limitation: if k is less than or equal to g the formula blows up. Does not work for companies without dividends.',
    'gordon_target': 'Ideal method for passive income investors',
    'anr_expander': '4  NAV — Net Asset Value (Patrimonial Approach)',
    'anr_title': 'The real net asset value',
    'anr_concept': "What would remain for shareholders if the company sold all assets and repaid all debts? We look at the balance sheet. This is Benjamin Graham's method, the father of value investing.",
    'anr_variants': 'Book Value (P/B): simple accounting version | Graham Net-Net: stock trades below net current assets | Real estate NAV: properties revalued at market prices',
    'anr_usecase': 'Use case: Holding companies, real estate (REITs), heavy industrials, distressed companies.',
    'anr_warning': 'Limitation: does not account for future earnings capacity. A company may appear low-value on paper but generate enormous cash.',
    'anr_target': 'Deep Value method — foundation of the Benjamin Graham approach',
    'convergence_title': 'Method convergence: the most reliable signal',
    'convergence_body': 'When multiple methods converge on the same fair value, conviction is much stronger. A large divergence signals high uncertainty or an assumption to revisit.',
    'wacc_expander': 'WACC — Discount Rate (DCF only)',
    'wacc_title': 'Weighted Average Cost of Capital (WACC)',
    'wacc_concept': 'WACC is the rate at which future cash flows are discounted to today. The higher it is, the lower the calculated value. A 1% change can alter the valuation by 15-30%.',
    'wacc_variables': 'ke = Risk-free rate + beta × Market premium | kd = cost of debt | t = tax rate | beta = relative volatility vs market',
    'wacc_ranges': 'Large stable cap (beta≈0.8): 7-9% | Cyclical (beta≈1.2): 10-12% | Small cap high growth (beta≈1.5): 13-16% | Highly leveraged: add 1-3%',
    'wacc_auto': 'SigmaScope automatically estimates WACC: Risk-free rate (4%) + beta × 5% + debt spread. This estimate is indicative.',
    'wacc_target': 'Sensitivity: ±1% on k → ±15-25% on value',
    'g_expander': 'g — Perpetual Growth Rate (DCF only)',
    'g_title': 'Terminal growth rate',
    'g_concept': 'The terminal value represents 60-80% of total DCF value. The g parameter is the most sensitive in the model. It must always be below WACC, otherwise the formula produces infinite values.',
    'g_rules': 'g should never exceed nominal GDP growth (≈ 2-3%) | Tech/software: 2.5-3% | Heavy industry: 1-1.5% | Emerging markets: 3-4%',
    'g_warning': 'A g of 4% with WACC of 10% gives a terminal value 2x higher than g of 2%. Always test 3 scenarios: pessimistic (1%), central (2.5%), optimistic (4%).',
    'g_target': 'Golden rule: g below WACC and below GDP growth',
    'k_gordon_expander': 'k — Required Return Gordon-Shapiro (DDM only)',
    'k_gordon_title': 'Required rate of return by the shareholder',
    'k_gordon_concept': 'In Gordon-Shapiro, k is the minimum return the investor requires to hold the stock. Same role as WACC in DCF but applies only to equity.',
    'k_gordon_calibration': 'Cautious investor: k = 5-7% | Balanced: k = 7-9% | Growth: k = 9-12% | Absolute constraint: k must exceed g',
    'k_gordon_warning': 'Example: k=8%, g=3% spread=5% | k=6%, g=4% spread=2%: value is 2.5x higher with same dividend. Sensitivity is extreme when k-g spread is small.',
    'k_gordon_target': 'Sensitivity: if k-g spread halves, value doubles',
    'horizon_expander': 'DCF Horizon — Number of projection years (DCF only)',
    'horizon_title': 'Explicit projection horizon',
    'horizon_concept': 'The horizon is the period over which FCF is projected before applying terminal value. Too short underestimates high-growth companies.',
    'horizon_reco': '5 years: cyclical sectors | 10 years: standard recommended | 15-20 years: high growth with durable competitive advantage',
    'horizon_warning': 'Beyond 10 years, FCF forecast accuracy decreases sharply. Build multiple scenarios rather than extending the horizon.',
    'horizon_target': 'Recommended default: 10 years for most cases',
    'sensitivity_title': 'Sensitivity table — Parameter impact',
    'sensitivity_caption': 'Parameters marked increases strongly are the most sensitive — test them in pessimistic/optimistic scenarios before any investment decision.',
    'sensitivity_param': 'Parameter',
    'sensitivity_method': 'Method',
    'sensitivity_effect': 'Effect of increase',
    'sensitivity_range': 'Typical range',

}
