# ============================================================
# SIGMASCOPE — Çeviri sözlüğü TÜRKÇE
# ============================================================

TRANSLATIONS = {

    # ── Dil ──────────────────────────────────────────────────
    "lang_selector_label": "🌐 Langue / Language / Dil",
    "lang_fr": "🇫🇷 Français",
    "lang_en": "🇬🇧 English",
    "lang_tr": "🇹🇷 Türkçe",

    # ── Kenar çubuğu ─────────────────────────────────────────
    "sidebar_title":        "🚀 SigmaScope - jp tarafından",
    "sidebar_nav":          "### 🗂️ Gezinti",
    "sidebar_indices":      "**📂 Yüklü endeksler**",
    "sidebar_no_index":     "⚠️ Yüklü endeks yok.\n⚙️ Yapılandırma sayfasına gidin.",
    "sidebar_valeurs":      "değer",
    "sidebar_stop":         "⏹️ Uygulamayı durdur",
    "sidebar_stop_help":    "Streamlit sunucusunu durdurur",
    "sidebar_stopping":     "Durduruluyor…",

    # ── Sayfa gezintisi ──────────────────────────────────────
    "page_presentation":    "🏠 Genel Bakış",
    "page_analyse":         "📈 Hisse analizi",
    "page_watchlists":      "⭐ İzleme listeleri",
    "page_comparaison":     "🔀 Karşılaştırma",
    "page_screener_sigma":  "🔭 Sigma Tarayıcı",
    "page_screener_multi":  "🎛️ Çok kriterli tarayıcı",
    "page_explications":    "📖 Belgeler",
    "page_configuration":   "⚙️ Yapılandırma",

    # ── Genel Bakış — Hero ───────────────────────────────────
    "hero_tagline":         "Hepsi bir arada kantitatif borsa analiz platformu",
    "hero_tagline2":        "Log regresyon · Temel analiz · Tarayıcı · DCF değerleme",
    "hero_version":         "✨ Sürüm 24 — jp tarafından",
    "hero_pp_compat":       "🤝 Uyumlu:",
    "hero_pp_desc":         "— portföyünüzü doğrudan içe aktarın (XML dosyası)",

    # ── Genel Bakış — Özellikler ─────────────────────────────
    "feat_title":           "### 🧩 Ana özellikler",
    "feat_open_analyse":    "→ Hisse analizini aç",
    "feat_open_watchlist":  "→ İzleme listelerini aç",
    "feat_open_comparaison":"→ Karşılaştırmayı aç",
    "feat_open_screener_s": "→ Sigma Tarayıcıyı aç",
    "feat_open_screener_m": "→ Çok kriterli tarayıcıyı aç",
    "feat_open_valorisation":"→ Hisse analizinde görüntüle",

    # ── Genel Bakış — İstatistik rozetleri ───────────────────
    "stat_modules":         "Analiz modülleri",
    "stat_indices":         "Yüklü endeksler",
    "stat_tickers":         "Önceden yüklü hisseler (∞ Yahoo Finance)",
    "stat_methods":         "Değerleme yöntemleri",
    "stat_sigma_zones":     "Tespit edilen sigma bölgeleri",

    # ── Genel Bakış — Hızlı başlangıç ───────────────────────
    "quickstart_title":     "### 🚀 Hızlı başlangıç",
    "sigma_zones_title":    "### 📐 Sigma bölgelerini anlamak",

    # ── Genel Bakış — Yol haritası ───────────────────────────
    "roadmap_expander":     "🛠️ Yol haritası & planlanan özellikler",
    "roadmap_title":        "#### 🚧 Geliştirme aşamasında / yakında",
    "roadmap_legend_high":  "🔴 Yüksek öncelik",
    "roadmap_legend_study": "🟢 İnceleniyor",
    "roadmap_caption":      "💡 Aşağıdaki **Öneriler** bölümünde en çok neyin işinize yarayacağını söyleyin!",
    "roadmap_item1_title":  "Gerçek değer hesabının gözden geçirilmesi",
    "roadmap_item1_desc":   "**DCF, Gordon-Shapiro, Katlar ve NAV** yöntemlerinin kapsamlı incelemesi — formül tutarlılığının, varsayılan parametrelerin ve sonuçların finansal değerleme standartlarıyla doğrulanması.",
    "roadmap_item2_title":  "Google kimlik doğrulaması",
    "roadmap_item2_desc":   "Anonim token'ı **gerçek bir Google hesabıyla** değiştirme — herhangi bir cihazdan izleme listelerinize erişmek için. Bu sizin için önemliyse bir yorum bırakın 👇",
    "roadmap_item3_title":  "Veri dışa aktarma",
    "roadmap_item3_desc":   "İzleme listeleri ve analiz sonuçlarını **CSV / Excel** olarak dışa aktarma. Buna ihtiyacınız varsa bir yorum bırakın 👇",
    "roadmap_item4_title":  "Gelişmiş tarayıcı",
    "roadmap_item4_desc":   "Çok kriterli tarayıcıya teknik filtreler (RSI, Bollinger) ekleme. Bu işinize yarayacaksa bir yorum bırakın 👇",
    "roadmap_item5_title":  "Yahoo Finance kararlılığı",
    "roadmap_item5_desc":   "Yahoo Finance hız sınırlaması aralıklı hatalara yol açabilir. Resmi bir yedek API inceleniyor. Bu sorunla sık karşılaşıyorsanız bir yorum bırakın 👇",
    "roadmap_item6_title":  "Tam web sitesine geçiş",
    "roadmap_item6_desc":   "Kullanım bunu gerektiriyorsa **tam web uygulamasına** (FastAPI + React) geçiş planlanıyor. Aşağıda oy verin ve yorum bırakın 👇",

    # ── Genel Bakış — İstatistikler & puanlama ───────────────
    "stats_expander":           "📊 Kullanım istatistikleri",
    "stats_users":              "Benzersiz kullanıcılar",
    "stats_sessions":           "Toplam oturum",
    "stats_duration":           "Ort. oturum süresi",
    "stats_rating":             "değerlendirme",
    "stats_saas_vote":          "Web sitesi geçiş oyu",
    "stats_rating_title":       "#### ⭐ Uygulamayı puanlayın",
    "stats_your_note":          "Puanınız",
    "stats_saas_question":      "SigmaScope tam bir web sitesine dönüştürülmeli mi?",
    "stats_saas_yes":           "✅ Evet, tam bir web sitesine dönüştür",
    "stats_saas_no":            "❌ Hayır, Streamlit uygulaması yeterli",
    "stats_save_btn":           "💾 Değerlendirmemi kaydet",
    "stats_save_ok":            "✅ Teşekkürler! Puan: {stars} — SaaS oyu: {vote}",
    "stats_save_oui":           "Evet",
    "stats_save_non":           "Hayır",
    "stats_save_err":           "❌ Kaydedilirken hata oluştu.",

    # ── Genel Bakış — Öneriler ───────────────────────────────
    "feedback_expander":        "💬 Öneriler & iyileştirmeler",
    "feedback_title":           "#### 📝 Mesaj bırakın",
    "feedback_visibility":      "Mesaj görünürlüğü",
    "feedback_public":          "🌐 Herkese açık — herkes görebilir",
    "feedback_private":         "🔒 Özel — yalnızca yönetici görebilir",
    "feedback_caption_private": "🔒 Bu mesaj yalnızca yönetici tarafından görülebilir.",
    "feedback_caption_public":  "🌐 Bu mesaj tüm kullanıcılar tarafından görülebilir.",
    "feedback_placeholder":     "Örn.: MACD göstergesi ekle, tarayıcı sayfasını geliştir...",
    "feedback_send_btn":        "📤 Gönder",
    "feedback_ok_private":      "✅ Özel mesaj yöneticiye gönderildi, teşekkürler!",
    "feedback_ok_public":       "✅ Herkese açık mesaj gönderildi, teşekkürler!",
    "feedback_err":             "❌ Gönderilirken hata oluştu.",
    "feedback_empty":           "⚠️ Mesaj boş olamaz.",
    "feedback_community_title": "#### 💡 Topluluk önerileri",
    "feedback_none":            "Henüz öneri yok — ilk siz olun!",

    # ── Alt bilgi ────────────────────────────────────────────
    "footer_text":  "⚡ SigmaScope veri kaynağı olarak <strong style=\"color:#4C9BE8;\">Yahoo Finance</strong> kullanır · Kantitatif analiz için tasarlanmıştır · <em>Yatırım tavsiyesi değildir</em>",

    # ── Hisse analizi sayfası ─────────────────────────────────
    "analyse_title":            "📈 Hisse analizi",
    "analyse_params_expander":  "🔍 Analiz parametreleri",
    "analyse_ticker_label":     "Sembol / Şirket",
    "analyse_ticker_help":      "Tüm yüklü endekslerde filtreleyerek arama",
    "analyse_ticker_placeholder":"Sembol (AAPL) veya şirket adı (Apple) yazın…",
    "analyse_ticker_manual":    "Manuel sembol",
    "analyse_ticker_manual_ph": "örn.: AAPL, BNP.PA…",
    "analyse_indice_label":     "Endeks / izleme listesi seçin",
    "analyse_composant_label":  "Bileşen ({n} değer)",
    "analyse_no_index":         "⚠️ Veri yok. ⚙️ Yapılandırma sayfasına gidin.",
    "analyse_choose_index":     "— önce bir endeks seçin —",
    "analyse_period_label":     "Dönem",
    "analyse_ticker_selected":  "Seçilen sembol:",
    "analyse_launch_btn":       "🚀 Analizi Başlat",
    "analyse_loading":          "Veriler yükleniyor…",
    "analyse_no_data":          "Bu sembol için veri yok.",
    "analyse_error":            "Hata: {e}",
    "analyse_configure_first":  "👆 Yukarıdan bir sembol seçin, ardından **🚀 Analizi Başlat** butonuna tıklayın.",

    # ── Analiz — alt bölümler ────────────────────────────────
    "analyse_tech_expander":    "📊 Teknik Analiz",
    "analyse_fair_expander":    "💰 Tarihsel Gerçek Değer",
    "analyse_score_expander":   "📊 Temel Karne & Genel Skor",
    "analyse_histo_expander":   "📊 Tarihsel Temel Göstergeler",
    "analyse_info_expander":    "🏢 Şirket bilgileri",
    "analyse_trend_expander":   "📈 Trend Analizi",
    "analyse_adv_params":       "⚙️ Gelişmiş parametreler",

    # ── Analiz — Teknik ──────────────────────────────────────
    "tc_period_warning":        "⚠️ Dönem **{period}** ile sınırlı, granülarite: {interval}.",
    "tc_no_data":               "Bu sembol için veri yok.",
    "tc_chart_err":             "Teknik grafik yüklenirken hata: {e}",

    # ── Analiz — Gerçek Değer ────────────────────────────────
    "fv_no_data":               "ℹ️ Bu yöntemle gerçek değer hesaplamak için yeterli veri yok ({method}).",
    "fv_no_fetch":              "⚠️ Gerçek değer hesaplamak için veriler alınamadı.",

    # ── İzleme listeleri ─────────────────────────────────────
    "wl_title":                 "⭐ İzleme Listelerim",
    "wl_info":                  "🔑 **İzleme listeleriniz** tarayıcınıza bağlı benzersiz anonim bir token ile güvenli veritabanında saklanmaktadır (token: `{uid}`).  \n📌 İzleme listelerinize her zaman erişmek için **bu sayfayı yer imlerinize ekleyin** — URL token'ınızı içerir.  \n⚠️ **Son kullanma tarihi**: **30 gün** geri dönmezseniz izleme listeleriniz otomatik olarak silinir.",
    "wl_manage_expander":       "🗂️ İzleme listesi yönetimi",
    "wl_active_label":          "📋 Aktif izleme listesi",
    "wl_new_btn":               "➕ Yeni",
    "wl_delete_btn":            "🗑️ Sil",
    "wl_delete_help":           "'{name}' izleme listesini sil",
    "wl_import_btn":            "📥 İçe aktar",
    "wl_import_help":           "Portfolio Performance'dan portföy içe aktar (.xml)",
    "wl_delete_confirm_msg":    "⚠️ **{name}** izleme listesini ve tüm kayıtlarını silmek istiyor musunuz?",
    "wl_delete_confirm_btn":    "🗑️ Silmeyi onayla",
    "wl_delete_cancel_btn":     "❌ İptal",
    "wl_autosave":              "💾 **{name}** — otomatik kaydediliyor",
    "wl_add_expander":          "➕ Manuel olarak hisse ekle",
    "wl_add_ticker_label":      "Sembol",
    "wl_add_ticker_ph":         "örn.: AAPL, BNP.PA",
    "wl_add_btn":               "➕ Ekle",
    "wl_add_ok":                "✅ {ticker} izleme listesine eklendi!",
    "wl_add_duplicate":         "{ticker} zaten izleme listesinde.",
    "wl_add_empty":             "Bir sembol girin.",
    "wl_empty_info":            "👆 İzleme listeniz boş. Herhangi bir sayfadaki **⭐ İzleme listesi** butonu veya yukarıdan manuel olarak hisse ekleyin.",
    "wl_refresh_btn":           "🔄 Verileri yenile",
    "wl_data_errors":           "⚠️ Veri mevcut değil: {tickers}",
    "wl_analyse_tip":           "💡 Bireysel hisse analizi başlatmak için soldaki **📈** kutusunu işaretleyin",
    "wl_sigma_expander":        "📈 İzleme listesi grafiği (sigma konumları)",
    "wl_pru_expander":          "💰 İzleme listesi grafiği (fiyat - ortalama maliyet)",
    "wl_manage2_expander":      "⚙️ İzleme listesi yönetimi",
    "wl_remove_tip":            "💡 Hisseyi izleme listesinden silmek için **🗑️ Kaldır** kutusunu işaretleyin",
    "wl_edit_expander":         "✏️ Not / alış fiyatı ekle",
    "wl_save_edit_btn":         "💾 Kaydet",
    "wl_edit_ok":               "✅ Güncellendi.",
    "wl_sigma_no_data":         "Sigma verisi mevcut değil.",
    "wl_pru_no_data":           "Bu izleme listesinde alış fiyatı girilmemiş.",

    # ── Karşılaştırma ────────────────────────────────────────
    "comp_title":               "🔀 Hisse Karşılaştırması",
    "comp_params_expander":     "🔍 Karşılaştırma parametreleri",
    "comp_selected":            "**Seçilen hisseler:** {tickers}",
    "comp_no_data":             "Veri mevcut değil.",
    "comp_table_title":         "📋 Performans tablosu",
    "comp_tip":                 "💡 Bireysel analiz için **📈 Analiz Et** kutusunu · Eklemek/çıkarmak için **⭐ İzleme listesi** kutusunu işaretleyin",
    "comp_configure_first":     "👆 Hisseleri seçin, ardından **📊 Karşılaştır** butonuna tıklayın.",

    # ── Sigma Tarayıcı ───────────────────────────────────────
    "screener_sigma_title":     "🔭 Sigma Tarayıcı — Endeks hisselerini tara",
    "screener_sigma_params":    "🔍 Tarama parametreleri",
    "screener_sigma_no_index":  "⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.",
    "screener_sigma_launch":    "🔍 Taramayı başlat",
    "screener_sigma_scanning":  "🔄 **{index}** endeksinden **{n}** hisse taranıyor, dönem: **{period}** — bölgeler: **{zones}**",
    "screener_sigma_errors":    "⚠️ Veri mevcut değil: {tickers}",
    "screener_sigma_no_result": "Seçilen bölgeler için hisse bulunamadı.",
    "screener_sigma_found":     "✅ **{n} hisse bulundu**  •  {index}  •  {period}",
    "screener_sigma_tip":       "💡 Analiz başlatmak için **📈 Analiz Et** · İzleme listesine eklemek/çıkarmak için **⭐ IL** kutusunu işaretleyin",
    "screener_sigma_charts":    "📈 Grafikler — {n} hisse",
    "screener_sigma_log_warn":  "⚠️ % değişim log ölçeğiyle uyumsuz",
    "screener_sigma_select_zone":"👆 En az bir bölge seçin, ardından **🔍 Taramayı başlat** butonuna tıklayın.",

    # ── Çok kriterli tarayıcı ────────────────────────────────
    "screener_multi_title":     "🎛️ Çok kriterli tarayıcı",
    "screener_multi_params":    "🔍 Tarayıcı parametreleri",
    "screener_multi_no_index":  "⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.",
    "screener_multi_launch":    "🚀 Tarayıcıyı başlat",
    "screener_multi_reset":     "↺ Filtreleri sıfırla",
    "screener_multi_no_sigma":  "ℹ️ Sigma bölgesi seçilmedi = tüm bölgeler kabul edildi.",
    "screener_multi_scanning":  "🔄 **{index}** endeksinden **{n}** hisse taranıyor — veriler yükleniyor…",
    "screener_multi_errors":    "⚠️ Hatalar: {tickers}",

    # ── Belgeler sayfası ─────────────────────────────────────
    "explain_title":            "📖 Göstergeler ve değerleme yöntemleri rehberi",
    "explain_scoring_title":    "### 📊 Puanlama Göstergeleri",
    "explain_valuation_title":  "### 💰 Değerleme: Bir Hissenin Gerçek Değeri Nasıl Hesaplanır?",
    "explain_params_title":     "### ⚙️ Değerleme Parametreleri Rehberi",
    "explain_sensitivity_cap":  "💡 **Güçlü artış** olarak işaretlenenler en hassas parametrelerdir — herhangi bir yatırım kararından önce kötümser/iyimser senaryolarda test edin.",

    # ── Yapılandırma sayfası ─────────────────────────────────
    "config_title":             "⚙️ Yapılandırma — Endeks yönetimi",
    "config_indices_title":     "📊 Yüklü endeksler durumu",
    "config_preview_title":     "🔍 Bileşen önizleme",
    "config_preview_select":    "Bileşenleri göster",
    "config_choose_index":      "-- Endeks seçin --",
    "config_no_index":          "ℹ️ Yüklü endeks yok. Güncellemek için yönetici olarak giriş yapın.",
    "config_admin_title":       "🔐 Yönetim",
    "config_admin_caption":     "Bu bölüm yalnızca yöneticiye ayrılmıştır.",
    "config_admin_pwd_ph":      "••••••••",
    "config_admin_login_btn":   "🔑 Giriş",
    "config_admin_err":         "❌ Hatalı şifre.",
    "config_admin_ok":          "✅ Yönetici modu etkinleştirildi",
    "config_admin_logout":      "🔓 Çıkış",
    "config_wiki_expander":     "🔄 Wikipedia endekslerini güncelle",
    "config_wiki_desc":         "Borsa endeksi bileşenlerini Wikipedia'dan yeniden yükleyin.",
    "config_wiki_select":       "Güncellenecek endeks",
    "config_wiki_none":         "-- Hiçbiri --",
    "config_wiki_btn":          "🔄 Güncelle",
    "config_wiki_btn_help":     "Bu endeksi Wikipedia'dan yeniden yükle",
    "config_wiki_source":       "🌐 Kaynak:",
    "config_wiki_ok":           "✅ {label} için {n} bileşen kaydedildi.",
    "config_wiki_err":          "Kazıma hatası: {e}",
    "config_wiki_select_first": "Lütfen önce bir endeks seçin.",
    "config_wiki_loading":      "{label} yükleniyor…",
    "config_sys_expander":      "ℹ️ Sistem bilgileri",
    "config_cache_btn":         "🧹 Market önbelleğini temizle (> 2s)",
    "config_cache_ok":          "✅ Önbellek temizlendi.",
    "config_private_expander":  "🔒 Özel kullanıcı mesajları",
    "config_private_none":      "Henüz özel mesaj yok.",
    "config_purge_expander":    "🗑️ Pasif izleme listesi temizliği",
    "config_purge_caption":     "30 günden fazla giriş yapmayan kullanıcıların izleme listelerini (ve içeriklerini) siler. ⚠️ Geri alınamaz işlem.",
    "config_purge_btn":         "🗑️ Pasif izleme listelerini temizle (> 30g)",
    "config_purge_ok":          "✅ {n} pasif izleme listesi silindi.",
    "config_purge_none":        "ℹ️ Silinecek pasif izleme listesi yok.",

    # ── Portfolio Performance içe aktarma ────────────────────
    "pp_dialog_title":          "📥 Portfolio Performance'dan İçe Aktar",
    "pp_step1":                 "📂 Yükleme",
    "pp_step2":                 "🏦 Hesap",
    "pp_step3":                 "✅ Onay",
    "pp_upload_label":          "**Portfolio Performance XML dosyasını yükleyin**",
    "pp_upload_caption":        "Portfolio Performance'da *Dosya → Farklı kaydet…* menüsü.",
    "pp_upload_info":           "👆 Yukarıdan Portfolio Performance dosyanızı (.xml) seçin.",
    "pp_upload_close":          "❌ Kapat",
    "pp_upload_err":            "❌ Ayrıştırma hatası: {e}",
    "pp_select_label":          "**İçe aktarılacak hesabı seçin**",
    "pp_select_account":        "Hesap",
    "pp_select_pru_note":       "ℹ️ Ortalama maliyetler EUR cinsindendir (Portfolio Performance para birimi) ve olduğu gibi içe aktarılacaktır.",
    "pp_next_btn":              "▶️ İleri",
    "pp_back_btn":              "◀️ Geri",
    "pp_cancel_btn":            "❌ İptal",
    "pp_confirm_label":         "**İzleme listesini adlandırın ve içe aktarmayı onaylayın**",
    "pp_wl_name_label":         "İzleme listesi adı",
    "pp_wl_name_help":          "Bu adla yeni bir izleme listesi oluşturulacak (varsa değiştirilecek).",
    "pp_wl_exists":             "⚠️ **{name}** izleme listesi zaten var — içeriği **değiştirilecek**.",
    "pp_wl_new":                "✨ **{name}** adında yeni bir izleme listesi oluşturulacak.",
    "pp_import_btn":            "📥 İçe aktar",
    "pp_import_empty_name":     "Ad boş olamaz.",
    "pp_import_ok":             "✅ **{name}** listesine {n} pozisyon içe aktarıldı!",

    # ── İzleme listesi diyaloğu ──────────────────────────────
    "wl_dialog_title":          "🗂️ Bu sembolü hangi izleme listesine ekleyeceksiniz?",
    "wl_dialog_add_label":      "**`{ticker}`** ({company}) izleme listesine ekle:",
    "wl_dialog_target":         "Hedef izleme listesi",
    "wl_dialog_already":        "⚠️ `{ticker}` zaten **{name}** listesinde.",
    "wl_dialog_add_btn":        "✅ Ekle",
    "wl_dialog_cancel_btn":     "❌ İptal",
    "wl_dialog_add_ok":         "⭐ {ticker} **{name}** listesine eklendi!",
    "wl_dialog_remove_msg":     "**`{ticker}`** sembolünü **{name}** listesinden çıkar?",
    "wl_dialog_remove_btn":     "🗑️ Çıkar",
    "wl_dialog_remove_ok":      "❌ {ticker} izleme listesinden çıkarıldı",
    "wl_btn_add":               "⭐ İzleme listesi",
    "wl_btn_in":                "✅ İzleme listesi",
    "wl_btn_add_help":          "İzleme listesine ekle ({name})",
    "wl_btn_remove_help":       "İzleme listesinden çıkar ({name})",

    # ── Supabase / bağlantı ──────────────────────────────────
    "supabase_err":             "❌ Supabase bağlantısı kurulamadı: {e}",

    # ── Genel ────────────────────────────────────────────────
    "min_suffix":               "dk",
    "values_suffix":            "değer",
    "loading":                  "Yükleniyor…",
    "error_prefix":             "Hata: ",
}
