# ============================================================
# SIGMASCOPE — Çeviri sözlüğü TÜRKÇE
# ============================================================

TRANSLATIONS = {

    # ── Dil ──────────────────────────────────────────────────
    "lang_selector_label": "🌐 Langue / Language / Dil",
    "lang_fr": "🇫🇷 Français",
    "lang_en": "🇬🇧 English",
    "lang_tr": "🇹🇷 Türkçe",

    # ── Kenar çubuğu ─────────────────────────────────────────
    "sidebar_title":        "🚀 SigmaScope - jp tarafından",
    "sidebar_nav":          "### 🗂️ Gezinti",
    "sidebar_indices":      "**📂 Yüklü endeksler**",
    "sidebar_no_index":     "⚠️ Yüklü endeks yok.\n⚙️ Yapılandırma sayfasına gidin.",
    "sidebar_valeurs":      "değer",
    "sidebar_stop":         "⏹️ Uygulamayı durdur",
    "sidebar_stop_help":    "Streamlit sunucusunu durdurur",
    "sidebar_stopping":     "Durduruluyor…",

    # ── Sayfa gezintisi ──────────────────────────────────────
    "page_presentation":    "🏠 Genel Bakış",
    "page_analyse":         "📈 Hisse analizi",
    "page_watchlists":      "⭐ İzleme listeleri",
    "page_comparaison":     "🔀 Karşılaştırma",
    "page_screener_sigma":  "🔭 Sigma Tarayıcı",
    "page_screener_multi":  "🎛️ Çok kriterli tarayıcı",
    "page_explications":    "📖 Belgeler",
    "page_configuration":   "⚙️ Yapılandırma",

    # ── Genel Bakış — Hero ───────────────────────────────────
    "hero_tagline":         "Hepsi bir arada kantitatif borsa analiz platformu",
    "hero_tagline2":        "Log regresyon · Temel analiz · Tarayıcı · DCF değerleme",
    "hero_version":         "✨ Sürüm 24 — jp tarafından",
    "hero_pp_compat":       "🤝 Uyumlu:",
    "hero_pp_desc":         "— portföyünüzü doğrudan içe aktarın (XML dosyası)",

    # ── Genel Bakış — Özellikler ─────────────────────────────
    "feat_title":           "### 🧩 Ana özellikler",
    "feat_open_analyse":    "→ Hisse analizini aç",
    "feat_open_watchlist":  "→ İzleme listelerini aç",
    "feat_open_comparaison":"→ Karşılaştırmayı aç",
    "feat_open_screener_s": "→ Sigma Tarayıcıyı aç",
    "feat_open_screener_m": "→ Çok kriterli tarayıcıyı aç",
    "feat_open_valorisation":"→ Hisse analizinde görüntüle",

    # ── Genel Bakış — İstatistik rozetleri ───────────────────
    "stat_modules":         "Analiz modülleri",
    "stat_indices":         "Yüklü endeksler",
    "stat_tickers":         "Önceden yüklü hisseler (∞ Yahoo Finance)",
    "stat_methods":         "Değerleme yöntemleri",
    "stat_sigma_zones":     "Tespit edilen sigma bölgeleri",

    # ── Genel Bakış — Hızlı başlangıç ───────────────────────
    "quickstart_title":     "### 🚀 Hızlı başlangıç",
    "sigma_zones_title":    "### 📐 Sigma bölgelerini anlamak",

    # ── Genel Bakış — Yol haritası ───────────────────────────
    "roadmap_expander":     "🛠️ Yol haritası & planlanan özellikler",
    "roadmap_title":        "#### 🚧 Geliştirme aşamasında / yakında",
    "roadmap_legend_high":  "🔴 Yüksek öncelik",
    "roadmap_legend_study": "🟢 İnceleniyor",
    "roadmap_caption":      "💡 Aşağıdaki **Öneriler** bölümünde en çok neyin işinize yarayacağını söyleyin!",
    "roadmap_item1_title":  "Gerçek değer hesabının gözden geçirilmesi",
    "roadmap_item1_desc":   "**DCF, Gordon-Shapiro, Katlar ve NAV** yöntemlerinin kapsamlı incelemesi — formül tutarlılığının, varsayılan parametrelerin ve sonuçların finansal değerleme standartlarıyla doğrulanması.",
    "roadmap_item2_title":  "Google kimlik doğrulaması",
    "roadmap_item2_desc":   "Anonim token'ı **gerçek bir Google hesabıyla** değiştirme — herhangi bir cihazdan izleme listelerinize erişmek için. Bu sizin için önemliyse bir yorum bırakın 👇",
    "roadmap_item3_title":  "Veri dışa aktarma",
    "roadmap_item3_desc":   "İzleme listeleri ve analiz sonuçlarını **CSV / Excel** olarak dışa aktarma. Buna ihtiyacınız varsa bir yorum bırakın 👇",
    "roadmap_item4_title":  "Gelişmiş tarayıcı",
    "roadmap_item4_desc":   "Çok kriterli tarayıcıya teknik filtreler (RSI, Bollinger) ekleme. Bu işinize yarayacaksa bir yorum bırakın 👇",
    "roadmap_item5_title":  "Yahoo Finance kararlılığı",
    "roadmap_item5_desc":   "Yahoo Finance hız sınırlaması aralıklı hatalara yol açabilir. Resmi bir yedek API inceleniyor. Bu sorunla sık karşılaşıyorsanız bir yorum bırakın 👇",
    "roadmap_item6_title":  "Tam web sitesine geçiş",
    "roadmap_item6_desc":   "Kullanım bunu gerektiriyorsa **tam web uygulamasına** (FastAPI + React) geçiş planlanıyor. Aşağıda oy verin ve yorum bırakın 👇",

    # ── Genel Bakış — İstatistikler & puanlama ───────────────
    "stats_expander":           "📊 Kullanım istatistikleri",
    "stats_users":              "Benzersiz kullanıcılar",
    "stats_sessions":           "Toplam oturum",
    "stats_duration":           "Ort. oturum süresi",
    "stats_rating":             "değerlendirme",
    "stats_saas_vote":          "Web sitesi geçiş oyu",
    "stats_rating_title":       "#### ⭐ Uygulamayı puanlayın",
    "stats_your_note":          "Puanınız",
    "stats_saas_question":      "SigmaScope tam bir web sitesine dönüştürülmeli mi?",
    "stats_saas_yes":           "✅ Evet, tam bir web sitesine dönüştür",
    "stats_saas_no":            "❌ Hayır, Streamlit uygulaması yeterli",
    "stats_save_btn":           "💾 Değerlendirmemi kaydet",
    "stats_save_ok":            "✅ Teşekkürler! Puan: {stars} — SaaS oyu: {vote}",
    "stats_save_oui":           "Evet",
    "stats_save_non":           "Hayır",
    "stats_save_err":           "❌ Kaydedilirken hata oluştu.",

    # ── Genel Bakış — Öneriler ───────────────────────────────
    "feedback_expander":        "💬 Öneriler & iyileştirmeler",
    "feedback_title":           "#### 📝 Mesaj bırakın",
    "feedback_visibility":      "Mesaj görünürlüğü",
    "feedback_public":          "🌐 Herkese açık — herkes görebilir",
    "feedback_private":         "🔒 Özel — yalnızca yönetici görebilir",
    "feedback_caption_private": "🔒 Bu mesaj yalnızca yönetici tarafından görülebilir.",
    "feedback_caption_public":  "🌐 Bu mesaj tüm kullanıcılar tarafından görülebilir.",
    "feedback_placeholder":     "Örn.: MACD göstergesi ekle, tarayıcı sayfasını geliştir...",
    "feedback_send_btn":        "📤 Gönder",
    "feedback_ok_private":      "✅ Özel mesaj yöneticiye gönderildi, teşekkürler!",
    "feedback_ok_public":       "✅ Herkese açık mesaj gönderildi, teşekkürler!",
    "feedback_err":             "❌ Gönderilirken hata oluştu.",
    "feedback_empty":           "⚠️ Mesaj boş olamaz.",
    "feedback_community_title": "#### 💡 Topluluk önerileri",
    "feedback_none":            "Henüz öneri yok — ilk siz olun!",

    # ── Alt bilgi ────────────────────────────────────────────
    "footer_text":  "⚡ SigmaScope veri kaynağı olarak <strong style=\"color:#4C9BE8;\">Yahoo Finance</strong> kullanır · Kantitatif analiz için tasarlanmıştır · <em>Yatırım tavsiyesi değildir</em>",

    # ── Hisse analizi sayfası ─────────────────────────────────
    "analyse_title":            "📈 Hisse analizi",
    "analyse_params_expander":  "🔍 Analiz parametreleri",
    "analyse_ticker_label":     "Sembol / Şirket",
    "analyse_ticker_help":      "Tüm yüklü endekslerde filtreleyerek arama",
    "analyse_ticker_placeholder":"Sembol (AAPL) veya şirket adı (Apple) yazın…",
    "analyse_ticker_manual":    "Manuel sembol",
    "analyse_ticker_manual_ph": "örn.: AAPL, BNP.PA…",
    "analyse_indice_label":     "Endeks / izleme listesi seçin",
    "analyse_composant_label":  "Bileşen ({n} değer)",
    "analyse_no_index":         "⚠️ Veri yok. ⚙️ Yapılandırma sayfasına gidin.",
    "analyse_choose_index":     "— önce bir endeks seçin —",
    "analyse_period_label":     "Dönem",
    "analyse_ticker_selected":  "Seçilen sembol:",
    "analyse_launch_btn":       "🚀 Analizi Başlat",
    "analyse_loading":          "Veriler yükleniyor…",
    "analyse_no_data":          "Bu sembol için veri yok.",
    "analyse_error":            "Hata: {e}",
    "analyse_configure_first":  "👆 Yukarıdan bir sembol seçin, ardından **🚀 Analizi Başlat** butonuna tıklayın.",

    # ── Analiz — alt bölümler ────────────────────────────────
    "analyse_tech_expander":    "📊 Teknik Analiz",
    "analyse_fair_expander":    "💰 Tarihsel Gerçek Değer",
    "analyse_score_expander":   "📊 Temel Karne & Genel Skor",
    "analyse_histo_expander":   "📊 Tarihsel Temel Göstergeler",
    "analyse_info_expander":    "🏢 Şirket bilgileri",
    "analyse_trend_expander":   "📈 Trend Analizi",
    "analyse_adv_params":       "⚙️ Gelişmiş parametreler",

    # ── Analiz — Teknik ──────────────────────────────────────
    "tc_period_warning":        "⚠️ Dönem **{period}** ile sınırlı, granülarite: {interval}.",
    "tc_no_data":               "Bu sembol için veri yok.",
    "tc_chart_err":             "Teknik grafik yüklenirken hata: {e}",

    # ── Analiz — Gerçek Değer ────────────────────────────────
    "fv_no_data":               "ℹ️ Bu yöntemle gerçek değer hesaplamak için yeterli veri yok ({method}).",
    "fv_no_fetch":              "⚠️ Gerçek değer hesaplamak için veriler alınamadı.",

    # ── İzleme listeleri ─────────────────────────────────────
    "wl_title":                 "⭐ İzleme Listelerim",
    "wl_info":                  "🔑 **İzleme listeleriniz** tarayıcınıza bağlı benzersiz anonim bir token ile güvenli veritabanında saklanmaktadır (token: `{uid}`).  \n📌 İzleme listelerinize her zaman erişmek için **bu sayfayı yer imlerinize ekleyin** — URL token'ınızı içerir.  \n⚠️ **Son kullanma tarihi**: **30 gün** geri dönmezseniz izleme listeleriniz otomatik olarak silinir.",
    "wl_manage_expander":       "🗂️ İzleme listesi yönetimi",
    "wl_active_label":          "📋 Aktif izleme listesi",
    "wl_new_btn":               "➕ Yeni",
    "wl_delete_btn":            "🗑️ Sil",
    "wl_delete_help":           "'{name}' izleme listesini sil",
    "wl_import_btn":            "📥 İçe aktar",
    "wl_import_help":           "Portfolio Performance'dan portföy içe aktar (.xml)",
    "wl_delete_confirm_msg":    "⚠️ **{name}** izleme listesini ve tüm kayıtlarını silmek istiyor musunuz?",
    "wl_delete_confirm_btn":    "🗑️ Silmeyi onayla",
    "wl_delete_cancel_btn":     "❌ İptal",
    "wl_autosave":              "💾 **{name}** — otomatik kaydediliyor",
    "wl_add_expander":          "➕ Manuel olarak hisse ekle",
    "wl_add_ticker_label":      "Sembol",
    "wl_add_ticker_ph":         "örn.: AAPL, BNP.PA",
    "wl_add_btn":               "➕ Ekle",
    "wl_add_ok":                "✅ {ticker} izleme listesine eklendi!",
    "wl_add_duplicate":         "{ticker} zaten izleme listesinde.",
    "wl_add_empty":             "Bir sembol girin.",
    "wl_empty_info":            "👆 İzleme listeniz boş. Herhangi bir sayfadaki **⭐ İzleme listesi** butonu veya yukarıdan manuel olarak hisse ekleyin.",
    "wl_refresh_btn":           "🔄 Verileri yenile",
    "wl_data_errors":           "⚠️ Veri mevcut değil: {tickers}",
    "wl_analyse_tip":           "💡 Bireysel hisse analizi başlatmak için soldaki **📈** kutusunu işaretleyin",
    "wl_sigma_expander":        "📈 İzleme listesi grafiği (sigma konumları)",
    "wl_pru_expander":          "💰 İzleme listesi grafiği (fiyat - ortalama maliyet)",
    "wl_manage2_expander":      "⚙️ İzleme listesi yönetimi",
    "wl_remove_tip":            "💡 Hisseyi izleme listesinden silmek için **🗑️ Kaldır** kutusunu işaretleyin",
    "wl_edit_expander":         "✏️ Not / alış fiyatı ekle",
    "wl_save_edit_btn":         "💾 Kaydet",
    "wl_edit_ok":               "✅ Güncellendi.",
    "wl_sigma_no_data":         "Sigma verisi mevcut değil.",
    "wl_pru_no_data":           "Bu izleme listesinde alış fiyatı girilmemiş.",

    # ── Karşılaştırma ────────────────────────────────────────
    "comp_title":               "🔀 Hisse Karşılaştırması",
    "comp_params_expander":     "🔍 Karşılaştırma parametreleri",
    "comp_selected":            "**Seçilen hisseler:** {tickers}",
    "comp_no_data":             "Veri mevcut değil.",
    "comp_table_title":         "📋 Performans tablosu",
    "comp_tip":                 "💡 Bireysel analiz için **📈 Analiz Et** kutusunu · Eklemek/çıkarmak için **⭐ İzleme listesi** kutusunu işaretleyin",
    "comp_configure_first":     "👆 Hisseleri seçin, ardından **📊 Karşılaştır** butonuna tıklayın.",

    # ── Sigma Tarayıcı ───────────────────────────────────────
    "screener_sigma_title":     "🔭 Sigma Tarayıcı — Endeks hisselerini tara",
    "screener_sigma_params":    "🔍 Tarama parametreleri",
    "screener_sigma_no_index":  "⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.",
    "screener_sigma_launch":    "🔍 Taramayı başlat",
    "screener_sigma_scanning":  "🔄 **{index}** endeksinden **{n}** hisse taranıyor, dönem: **{period}** — bölgeler: **{zones}**",
    "screener_sigma_errors":    "⚠️ Veri mevcut değil: {tickers}",
    "screener_sigma_no_result": "Seçilen bölgeler için hisse bulunamadı.",
    "screener_sigma_found":     "✅ **{n} hisse bulundu**  •  {index}  •  {period}",
    "screener_sigma_tip":       "💡 Analiz başlatmak için **📈 Analiz Et** · İzleme listesine eklemek/çıkarmak için **⭐ IL** kutusunu işaretleyin",
    "screener_sigma_charts":    "📈 Grafikler — {n} hisse",
    "screener_sigma_log_warn":  "⚠️ % değişim log ölçeğiyle uyumsuz",
    "screener_sigma_select_zone":"👆 En az bir bölge seçin, ardından **🔍 Taramayı başlat** butonuna tıklayın.",

    # ── Çok kriterli tarayıcı ────────────────────────────────
    "screener_multi_title":     "🎛️ Çok kriterli tarayıcı",
    "screener_multi_params":    "🔍 Tarayıcı parametreleri",
    "screener_multi_no_index":  "⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.",
    "screener_multi_launch":    "🚀 Tarayıcıyı başlat",
    "screener_multi_reset":     "↺ Filtreleri sıfırla",
    "screener_multi_no_sigma":  "ℹ️ Sigma bölgesi seçilmedi = tüm bölgeler kabul edildi.",
    "screener_multi_scanning":  "🔄 **{index}** endeksinden **{n}** hisse taranıyor — veriler yükleniyor…",
    "screener_multi_errors":    "⚠️ Hatalar: {tickers}",

    # ── Belgeler sayfası ─────────────────────────────────────
    "explain_title":            "📖 Göstergeler ve değerleme yöntemleri rehberi",
    "explain_scoring_title":    "### 📊 Puanlama Göstergeleri",
    "explain_valuation_title":  "### 💰 Değerleme: Bir Hissenin Gerçek Değeri Nasıl Hesaplanır?",
    "explain_params_title":     "### ⚙️ Değerleme Parametreleri Rehberi",
    "explain_sensitivity_cap":  "💡 **Güçlü artış** olarak işaretlenenler en hassas parametrelerdir — herhangi bir yatırım kararından önce kötümser/iyimser senaryolarda test edin.",

    # ── Yapılandırma sayfası ─────────────────────────────────
    "config_title":             "⚙️ Yapılandırma — Endeks yönetimi",
    "config_indices_title":     "📊 Yüklü endeksler durumu",
    "config_preview_title":     "🔍 Bileşen önizleme",
    "config_preview_select":    "Bileşenleri göster",
    "config_choose_index":      "-- Endeks seçin --",
    "config_no_index":          "ℹ️ Yüklü endeks yok. Güncellemek için yönetici olarak giriş yapın.",
    "config_admin_title":       "🔐 Yönetim",
    "config_admin_caption":     "Bu bölüm yalnızca yöneticiye ayrılmıştır.",
    "config_admin_pwd_ph":      "••••••••",
    "config_admin_login_btn":   "🔑 Giriş",
    "config_admin_err":         "❌ Hatalı şifre.",
    "config_admin_ok":          "✅ Yönetici modu etkinleştirildi",
    "config_admin_logout":      "🔓 Çıkış",
    "config_wiki_expander":     "🔄 Wikipedia endekslerini güncelle",
    "config_wiki_desc":         "Borsa endeksi bileşenlerini Wikipedia'dan yeniden yükleyin.",
    "config_wiki_select":       "Güncellenecek endeks",
    "config_wiki_none":         "-- Hiçbiri --",
    "config_wiki_btn":          "🔄 Güncelle",
    "config_wiki_btn_help":     "Bu endeksi Wikipedia'dan yeniden yükle",
    "config_wiki_source":       "🌐 Kaynak:",
    "config_wiki_ok":           "✅ {label} için {n} bileşen kaydedildi.",
    "config_wiki_err":          "Kazıma hatası: {e}",
    "config_wiki_select_first": "Lütfen önce bir endeks seçin.",
    "config_wiki_loading":      "{label} yükleniyor…",
    "config_sys_expander":      "ℹ️ Sistem bilgileri",
    "config_cache_btn":         "🧹 Market önbelleğini temizle (> 2s)",
    "config_cache_ok":          "✅ Önbellek temizlendi.",
    "config_private_expander":  "🔒 Özel kullanıcı mesajları",
    "config_private_none":      "Henüz özel mesaj yok.",
    "config_purge_expander":    "🗑️ Pasif izleme listesi temizliği",
    "config_purge_caption":     "30 günden fazla giriş yapmayan kullanıcıların izleme listelerini (ve içeriklerini) siler. ⚠️ Geri alınamaz işlem.",
    "config_purge_btn":         "🗑️ Pasif izleme listelerini temizle (> 30g)",
    "config_purge_ok":          "✅ {n} pasif izleme listesi silindi.",
    "config_purge_none":        "ℹ️ Silinecek pasif izleme listesi yok.",

    # ── Portfolio Performance içe aktarma ────────────────────
    "pp_dialog_title":          "📥 Portfolio Performance'dan İçe Aktar",
    "pp_step1":                 "📂 Yükleme",
    "pp_step2":                 "🏦 Hesap",
    "pp_step3":                 "✅ Onay",
    "pp_upload_label":          "**Portfolio Performance XML dosyasını yükleyin**",
    "pp_upload_caption":        "Portfolio Performance'da *Dosya → Farklı kaydet…* menüsü.",
    "pp_upload_info":           "👆 Yukarıdan Portfolio Performance dosyanızı (.xml) seçin.",
    "pp_upload_close":          "❌ Kapat",
    "pp_upload_err":            "❌ Ayrıştırma hatası: {e}",
    "pp_select_label":          "**İçe aktarılacak hesabı seçin**",
    "pp_select_account":        "Hesap",
    "pp_select_pru_note":       "ℹ️ Ortalama maliyetler EUR cinsindendir (Portfolio Performance para birimi) ve olduğu gibi içe aktarılacaktır.",
    "pp_next_btn":              "▶️ İleri",
    "pp_back_btn":              "◀️ Geri",
    "pp_cancel_btn":            "❌ İptal",
    "pp_confirm_label":         "**İzleme listesini adlandırın ve içe aktarmayı onaylayın**",
    "pp_wl_name_label":         "İzleme listesi adı",
    "pp_wl_name_help":          "Bu adla yeni bir izleme listesi oluşturulacak (varsa değiştirilecek).",
    "pp_wl_exists":             "⚠️ **{name}** izleme listesi zaten var — içeriği **değiştirilecek**.",
    "pp_wl_new":                "✨ **{name}** adında yeni bir izleme listesi oluşturulacak.",
    "pp_import_btn":            "📥 İçe aktar",
    "pp_import_empty_name":     "Ad boş olamaz.",
    "pp_import_ok":             "✅ **{name}** listesine {n} pozisyon içe aktarıldı!",

    # ── İzleme listesi diyaloğu ──────────────────────────────
    "wl_dialog_title":          "🗂️ Bu sembolü hangi izleme listesine ekleyeceksiniz?",
    "wl_dialog_add_label":      "**`{ticker}`** ({company}) izleme listesine ekle:",
    "wl_dialog_target":         "Hedef izleme listesi",
    "wl_dialog_already":        "⚠️ `{ticker}` zaten **{name}** listesinde.",
    "wl_dialog_add_btn":        "✅ Ekle",
    "wl_dialog_cancel_btn":     "❌ İptal",
    "wl_dialog_add_ok":         "⭐ {ticker} **{name}** listesine eklendi!",
    "wl_dialog_remove_msg":     "**`{ticker}`** sembolünü **{name}** listesinden çıkar?",
    "wl_dialog_remove_btn":     "🗑️ Çıkar",
    "wl_dialog_remove_ok":      "❌ {ticker} izleme listesinden çıkarıldı",
    "wl_btn_add":               "⭐ İzleme listesi",
    "wl_btn_in":                "✅ İzleme listesi",
    "wl_btn_add_help":          "İzleme listesine ekle ({name})",
    "wl_btn_remove_help":       "İzleme listesinden çıkar ({name})",

    # ── Supabase / bağlantı ──────────────────────────────────
    "supabase_err":             "❌ Supabase bağlantısı kurulamadı: {e}",

    # ── Genel ────────────────────────────────────────────────
    "min_suffix":               "dk",
    "values_suffix":            "değer",
    "loading":                  "Yükleniyor…",
    "error_prefix":             "Hata: ",
    "analyse_launch_btn": "🚀 Analizi Başlat",
    "analyse_period_default": "10 Yıl",
    "analyse_data_not_found": "Bu sembol için veri bulunamadı.",
    "analyse_loading_fundamentals": "Temel veriler yükleniyor…",
    "analyse_ticker_selected_html": "Seçilen sembol:",
    "analyse_yahoo_link": "Yahoo Finance'te görüntüle →",
    "analyse_position_sigma": "📍 Güncel konum:",
    "chart_period_label": "Dönem",
    "chart_yaxis_label": "Y Ekseni",
    "chart_yaxis_linear": "Doğrusal",
    "chart_yaxis_log": "Logaritmik",
    "chart_yaxis_help": "Doğrusal: mutlak değerler  |  Logaritmik: uzun dönemler için daha uygun",
    "chart_display_label": "Y Gösterimi",
    "chart_display_cours": "Fiyat",
    "chart_display_pct": "% Değişim",
    "chart_display_help": "Fiyat: ham fiyat  |  % Değişim: dönem başından itibaren performans",
    "chart_display_log_disabled": "  ⚠️ Logaritmik ölçekte devre dışı",
    "chart_cours_title": "Fiyat",
    "tc_period_section": "**Dönem**",
    "tc_granularity_section": "**Granülarite**",
    "tc_indicators_section": "**Göstergeler**",
    "tc_ma_label": "Hareketli ortalamalar",
    "tc_bb_label": "Bollinger",
    "tc_rsi_label": "RSI",
    "tc_volume_label": "Hacim",
    "tc_ma_periods_section": "**HO Dönemleri**",
    "tc_bb_period_label": "BB Dönemi",
    "tc_bb_std_label": "BB Std sapma",
    "tc_options_section": "**Seçenekler**",
    "tc_hide_gaps_label": "Boşlukları gizle",
    "tc_hide_gaps_help": "Piyasanın kapalı olduğu dönemlerdeki (geceler, hafta sonları, tatiller) X ekseni boşluklarını kaldırır",
    "fv_method_label": "Değerleme yöntemi",
    "fv_granularity_label": "Granülarite",
    "fv_gran_monthly": "Aylık",
    "fv_gran_weekly": "Haftalık",
    "fv_gran_yearly": "Yıllık",
    "fv_overlay_label": "Gerçek fiyatı üst üste koy",
    "fv_auto_label": "Otomatik yöntem",
    "fv_auto_help": "Otomatik seçer: {method}",
    "fv_suggested": "Önerilen yöntem:",
    "fv_adv_params_caption": "Gri parametreler seçilen yönteme uygulanmaz. Varsayılan değerler beta, borç ve sektörden otomatik olarak tahmin edilir.",
    "fv_wacc_label": "WACC k (%)",
    "fv_g_label": "Sürekli büyüme g (%)",
    "fv_k_gs_label": "Gordon gerekli getiri (%)",
    "fv_horizon_label": "DCF ufku (yıl)",
    "fv_calc_spinner": "Gerçek değer hesaplanıyor…",
    "fv_dcf_only": "⚠️ Yalnızca DCF",
    "fv_gordon_only": "⚠️ Yalnızca Gordon-Shapiro",
    "fv_gap_overvalued": "{pct:.1f}% aşırı değerli",
    "fv_gap_undervalued": "{pct:.1f}% düşük değerli",
    "wl_create_name_label": "Yeni izleme listesi adı",
    "wl_create_btn": "✅ Oluştur",
    "wl_create_cancel": "İptal",
    "wl_name_empty_err": "Ad boş olamaz.",
    "wl_name_exists_err": "Bu ad zaten var.",
    "wl_created_ok": "✅ **{name}** izleme listesi oluşturuldu!",
    "wl_deleted_ok": "✅ İzleme listesi silindi.",
    "wl_loading_data": "Veriler yükleniyor…",
    "wl_loading_ticker": "{ticker} yükleniyor…",
    "wl_col_ticker": "Sembol",
    "wl_col_company": "Şirket",
    "wl_col_date": "Eklenme tarihi",
    "wl_col_note": "Not",
    "wl_col_pru": "Ort. maliyet (€)",
    "wl_col_price": "Fiyat (€)",
    "wl_col_change": "Günlük değ. (%)",
    "wl_col_sigma": "σ Konumu",
    "wl_col_score": "Skor",
    "wl_col_roic": "ROIC (%)",
    "wl_col_revenue": "Gelir büyüme (%)",
    "wl_col_fcfm": "SMN marjı (%)",
    "wl_col_debt": "Borç/SMN",
    "wl_col_peg": "PEG",
    "wl_col_pru_pct": "Ort. maliyet farkı (%)",
    "wl_col_remove": "🗑️ Çıkar",
    "wl_note_placeholder": "Serbest not…",
    "wl_pru_placeholder": "Alış fiyatı…",
    "wl_edit_ok": "✅ Güncellendi.",
    "wl_sigma_chart_title": "Sigma konumu — {period}",
    "wl_pru_chart_title": "Güncel fiyat (€) / Ortalama maliyet (€)",
    "wl_progress_init": "Veriler yükleniyor…",
    "wl_ticker_manual_label": "Manuel sembol ekle",
    "wl_ticker_ph": "örn.: AAPL, MC.PA, ^GSPC…",
    "wl_period_select": "Zaman ufku",
    "wl_add_from_index": "Yüklü endeksler / izleme listelerinden ekle",
    "wl_add_from_index_help": "'── Tümünü seç: … ──' satırları tüm hisseleri ekler. ⭐ girişleri izleme listelerinizdir.",
    "wl_compare_btn": "📊 Karşılaştır",
    "wl_load_market_data": "Piyasa verileri yükleniyor…",
    "wl_best_stock": "🥇 En iyi performans",
    "wl_worst_stock": "📉 En düşük performans",
    "wl_col_name": "Ad",
    "wl_col_perf": "Performans",
    "wl_col_vol": "Yıllık volatilite",
    "wl_col_drawdown": "Maks. Düşüş",
    "wl_col_analyse": "📈 Analiz",
    "wl_norm_price": "Normalleştirilmiş fiyat (baz 1)",
    "wl_no_data_comp": "Veri bulunamadı: {tickers}",
    "screener_sigma_period_label": "📅 Analiz dönemi",
    "screener_sigma_index_label": "📂 Taranacak endeks / izleme listesi",
    "screener_sigma_index_help": "⭐ girişleri izleme listelerinize karşılık gelir",
    "screener_sigma_zones_title": "**🎯 Aranacak bölgeler** *(bir veya birden fazla bölge seçin)*",
    "screener_sigma_col_ticker": "Sembol",
    "screener_sigma_col_company": "Şirket",
    "screener_sigma_col_sigma": "σ Konumu",
    "screener_sigma_col_roe": "ROE",
    "screener_sigma_col_zone": "Bölge",
    "screener_sigma_col_psycho": "Psikoloji",
    "screener_sigma_col_analyse": "📈 Analiz",
    "screener_sigma_col_wl": "⭐ IL",
    "screener_sigma_analyse_help": "Bu sembol için analiz başlatmak üzere işaretleyin",
    "screener_sigma_wl_help": "İzleme listesine ekle/çıkar",
    "screener_sigma_position": "Konum:",
    "screener_sigma_zone_lbl": "Bölge:",
    "screener_sigma_init": "Başlatılıyor…",
    "screener_sigma_analyse_progress": "{ticker} analiz ediliyor…",
    "screener_sigma_click_to_start": "👆 Analizi başlatmak için **🔍 Taramayı başlat** butonuna tıklayın.",
    "screener_multi_desc": "En iyi fırsatları belirlemek için **temel** kriterleri ve **sigma konumunu** birleştirin.",
    "screener_multi_scan_params": "🗂️ Tarama parametreleri",
    "screener_multi_period_label": "Analiz dönemi",
    "screener_multi_index_label": "Taranacak endeks / izleme listesi",
    "screener_multi_index_help": "⭐ girişleri izleme listelerinize karşılık gelir",
    "screener_multi_fund_filters": "📊 Temel filtreler",
    "screener_multi_rev_min": "Min gelir büyümesi (%)",
    "screener_multi_roic_min": "Min ROIC (%)",
    "screener_multi_fcfm_min": "Min SMN marjı (%)",
    "screener_multi_debt_max": "Maks Borç/SMN",
    "screener_multi_score_min": "Min genel skor (/10)",
    "screener_multi_sigma_filters": "🔭 Sigma filtreleri",
    "screener_multi_sigma_filters_note": "(kabul edilen bölgeleri işaretleyin)",
    "screener_multi_reset_help": "Tüm kaydırıcıları varsayılan değerlere sıfırla",
    "screener_multi_found": "✅ **{n} hisse** kriterlerinize uyuyor  •  {index}  •  {period}  •  *{total} yüklendi — gerçek zamanlı filtreleme*",
    "screener_multi_col_ticker": "Sembol",
    "screener_multi_col_company": "Şirket",
    "screener_multi_col_score": "Skor",
    "screener_multi_col_sigma": "σ Konumu",
    "screener_multi_col_zone": "Bölge",
    "screener_multi_col_rev": "Gelir büyüme",
    "screener_multi_col_roic": "ROIC",
    "screener_multi_col_roe": "ROE",
    "screener_multi_col_fcfm": "SMN marjı",
    "screener_multi_col_debt": "Borç/SMN",
    "screener_multi_col_pe": "F/K",
    "screener_multi_col_peg": "PEG",
    "screener_multi_col_analyse": "📈 Analiz",
    "screener_multi_col_wl": "⭐ IL",
    "screener_multi_analyse_help": "Bu sembol için analiz başlatmak üzere işaretleyin",
    "screener_multi_wl_help": "İzleme listesine ekle/çıkar",
    "screener_multi_charts_title": "📈 Grafikler — {n} seçili hisse",
    "screener_multi_configure_first": "👆 Filtreleri ayarlayın, ardından **🚀 Tarayıcıyı başlat** butonuna tıklayın.",
    "screener_multi_score_lbl": "Skor:",
    "screener_multi_init": "Başlatılıyor…",
    "screener_multi_progress": "{ticker} analiz ediliyor…",
    "chart_yaxis_help_short": "Doğrusal veya logaritmik",
    "chart_display_help_short": "Ham fiyat veya % değişim — % değişim logaritmik ölçekte kullanılamaz",
    "chart_display_help_scr": "Ham fiyat veya % değişim",
    "comp_ticker_manual_label": "Manuel sembol ekle",
    "comp_ticker_ph": "örn.: AAPL, MC.PA, ^GSPC…",
    "comp_period_label": "Zaman ufku",
    "comp_add_from_index": "Yüklü endeksler / izleme listelerinden ekle",
    "comp_add_from_index_help": "⭐ girişleri izleme listelerinize karşılık gelir",
    "comp_launch_btn": "📊 Karşılaştır",
    "comp_load_spinner": "Piyasa verileri yükleniyor…",
    "comp_best": "🥇 En iyi performans",
    "comp_worst": "📉 En düşük performans",
    "comp_norm_price": "Normalleştirilmiş fiyat (baz 1)",
    "comp_date_axis": "Tarih",
    "comp_col_ticker": "Sembol",
    "comp_col_name": "Ad",
    "comp_col_perf": "Performans",
    "comp_col_vol": "Yıllık volatilite",
    "comp_col_drawdown": "Maks. Düşüş",
    "comp_col_analyse": "📈 Analiz",
    "comp_col_wl": "⭐ İzleme listesi",
    "comp_analyse_help": "Bireysel analiz başlat",
    "comp_wl_help": "İzleme listesine ekle/çıkar",
    "comp_errors": "Veri bulunamadı: {tickers}",
    "explain_subtitle": "Karnelerde ve tarayıcıda kullanılan her metriği anlayın.",
    "scorecard_global_score": "7 temel kritere dayalı **genel skor**:",
    "score_grade_A": "Mükemmel kalite",
    "score_grade_B": "İyi kalite",
    "score_grade_C": "Ortalama kalite",
    "score_grade_D": "Düşük kalite",
    "score_grade_F": "Yetersiz kalite",
    "hist_growth_expander": "📈 Tarihsel Büyüme Göstergeleri",
    "hist_profit_expander": "💰 Tarihsel Kârlılık Göstergeleri",
    "hist_valuation_expander": "⚖️ Tarihsel Değerleme Göstergeleri",
    "hist_solidity_expander": "🏦 Tarihsel Finansal Güç Göstergeleri",
    "hist_synthesis_title": "📋 Gelir→SMN→Marj Özeti ({year})",
    "hist_no_synthesis": "Özet verisi yetersiz.",
    "company_sector": "Sektör",
    "company_industry": "Endüstri",
    "company_country": "Ülke",
    "company_employees": "Çalışan sayısı",
    "company_website": "Web sitesi",
    "company_description": "Açıklama",
    "pp_positions_count": "📊 **{name}** listesinde **{n} pozisyon**:",
    "pp_more_positions": "… ve {n} pozisyon daha gösterilmiyor.",
    "pp_import_count": "📥 **{name}** listesinden **{n} pozisyon** içe aktarılacak: Sembol, Ad, EUR ort. maliyet.",
    "config_wiki_select_index": "Güncellenecek endeks",
    "sigma_position_label": "📍 Güncel konum:",

    'guide_growth_title': '📈 Büyüme Göstergeleri',
    'guide_profit_title': '💰 Kârlılık Göstergeleri',
    'guide_valuation_title': '⚖️ Değerleme Göstergeleri',
    'guide_solidity_title': '🏦 Finansal Güç Göstergeleri',
    'guide_sigma_title': '📐 Sigma Göstergeleri (Regresyon Konumu)',
    'guide_rev_name': 'Gelir Büyümesi (CAGR)',
    'guide_rev_body': 'Yıllık ortalama gelir büyümesini ölçer. Güçlü büyüme pazar payı kazanan bir şirkete işaret eder. Dikkat: kârlılık olmadan yüksek büyüme nakit yakan bir şirkete işaret edebilir.',
    'guide_rev_target': '> yılda %10',
    'guide_rev_interp': '< %0: düşüş | %0-5: zayıf | %5-10: orta | > %10: güçlü | > %20: istisnai',
    'guide_fcf_name': 'Serbest Nakit Akışı Büyümesi (CAGR)',
    'guide_fcf_body': 'SMN büyümesi yatırımlar sonrası gerçekten üretilen nakittir. SMN gelirden hızlı büyüyen bir şirket marjlarını iyileştiriyor demektir. Değer yatırımcılarının favori göstergesi.',
    'guide_fcf_target': '> yılda %10',
    'guide_fcf_interp': 'İdeal: SMN büyümesi > gelir büyümesi (marj iyileşmesi)',
    'guide_roic_name': 'ROIC — Yatırılan Sermaye Getirisi',
    'guide_roic_body': 'Kâr üretmek için sermayenin ne kadar verimli kullanıldığını ölçer. Sürekli yüksek ROIC (> %15) güçlü rekabet avantajına işaret eder. Warren Buffett en önemli göstergelerden biri olarak kabul eder.',
    'guide_roic_target': '> %15',
    'guide_roic_interp': '< %8: zayıf | %8-15: orta | %15-25: güçlü | > %25: istisnai (hendek)',
    'guide_roe_name': 'ROE — Özkaynak Getirisi',
    'guide_roe_body': 'Özkaynak kârlılığını ölçer. Yüksek ve istikrarlı ROE, hissedar değeri yaratan bir şirkete işaret eder. Yüksek kaldıraçlı şirketlerde dikkatli yorumlanmalıdır.',
    'guide_roe_target': '> %15',
    'guide_roe_interp': '< %10: zayıf | %10-15: orta | %15-25: güçlü | > %25: istisnai | Negatif: zararlar',
    'guide_fcfm_name': 'Serbest Nakit Akışı Marjı',
    'guide_fcfm_body': 'Gelirin capex sonrası kullanılabilir nakite dönüşen yüzdesi. Yüksek SMN marjı düşük yatırım ihtiyacı olan bir şirkete işaret eder. Yazılım > %30, ağır sanayi < %5.',
    'guide_fcfm_target': '> %10',
    'guide_fcfm_interp': '< %5: zayıf | %5-10: orta | %10-20: güçlü | > %20: istisnai',
    'guide_pe_name': 'F/K Oranı — Fiyat/Kazanç',
    'guide_pe_body': 'Yatırımcının kaç yıllık kazanç ödediği. Her zaman sektör ve büyüme bağlamında yorumlanmalıdır. Yüksek büyüme gösteren bir şirket için yüksek F/K mutlaka pahalı değildir.',
    'guide_pe_target': 'Gösterge — sektöre bağlıdır',
    'guide_pe_interp': 'Teknoloji: 20-40x | Bankalar: 8-12x | Altyapı: 12-18x',
    'guide_peg_name': 'PEG Oranı — Fiyat/Kazanç/Büyüme',
    'guide_peg_body': "F/K'yı büyümeyle düzeltir: %30 büyüme ile 30 F/K, 1 PEG verir. Peter Lynch tarafından icat edilmiştir. PEG < 1 büyümesine göre düşük değerli hisseye işaret eder.",
    'guide_peg_target': '< 2 (ideal < 1)',
    'guide_peg_interp': '< 1: potansiyel düşük değerli | 1-2: adil fiyat | > 2: büyümesine göre pahalı',
    'guide_pb_name': 'Fiyat / Defter Değeri (F/DD)',
    'guide_pb_body': 'Piyasa değerini varlıkların defter değeriyle karşılaştırır. F/DD < 1, borsanın şirketi net varlıklarının altında değerlediği anlamına gelir.',
    'guide_pb_target': '< 5 (sektöre bağlıdır)',
    'guide_pb_interp': 'Bankalar: 0.5-1.5x | Teknoloji: 5-20x mümkün | < 1: varlık iskontosu',
    'guide_pfcf_name': 'Fiyat / Serbest Nakit Akışı (F/SMN)',
    'guide_pfcf_body': "F/K'dan manipüle edilmesi daha zordur. Yatırımcının gerçekten üretilen her euro nakit için ne ödediğini gösterir.",
    'guide_pfcf_target': '< 25',
    'guide_pfcf_interp': '< 15: potansiyel ucuz | 15-25: orta | > 25: pahalı | > 40: çok pahalı',
    'guide_debt_name': 'Net Borç / SMN',
    'guide_debt_body': "Net borcun üretilen SMN ile kaç yılda geri ödeneceğini ölçer. 3'ten küçük sağlıklı bir şirketi gösterir. Negatif: borçtan fazla nakit.",
    'guide_debt_target': '< 3 yıl',
    'guide_debt_interp': '< 0: pozitif net nakit | 0-3: sağlıklı | 3-5: dikkat | > 5: riskli',
    'guide_sigma_name': 'Sigma konumu',
    'guide_sigma_body': 'Güncel fiyatın uzun vadeli logaritmik trendinden sapmasını standart sapma cinsinden ölçer. Bir hissenin istatistiksel olarak aşırı alınmış mı satılmış mı olduğunu belirler.',
    'guide_sigma_target': 'Stratejiye bağlıdır',
    'guide_sigma_interp': '> +1.75: yüksek aşırılık | +0.75 ile +1.25: güçlü trend | 0 civarı nötr | < -1.75: düşük aşırılık (fırsatlar)',
    'guide_score_name': "Genel Skor (/10 — A'dan F'ye)",
    'guide_score_body': '7 ağırlıklı kritere göre sentetik not: Gelir büyümesi (x2), SMN (x2), ROIC (x2), SMN marjı (x1), Borç/SMN (x1), PEG (x1), F/DD (x1). A >= 8.5 | B >= 7.0 | C >= 5.5 | D >= 4.0 | F < 4.0.',
    'guide_score_target': '>= 7/10 (B notu veya daha iyi)',
    'guide_score_interp': 'Yüksek skor + düşük sigma = potansiyel alım fırsatı',
    'guide_strategy_title': '### 💡 Birleşik strateji: Skor + Sigma',
    'guide_strategy_body': 'Bu aracın en güçlü yaklaşımı, temel kaliteyi (genel skor) teknik zamanlamayla (sigma konumu) birleştirmektir:',
    'guide_strategy_screener': '> **Çok kriterli tarayıcı** bu kombinasyonu tüm bir endeks üzerinde otomatikleştirir.',
    'guide_target_lbl': '🎯 Hedef:',
    'explain_valuation_intro': 'Evrensel bir yöntem yoktur. Her yaklaşım farklı varsayımlara dayanır ve belirli bir şirket türüne uygundur. Büyük yatırımcılar bunları birleştirir.',
    'explain_params_intro': 'Her yöntem için temel varsayımları nasıl kalibre edeceğinizi ve duyarlılıklarını öğrenin.',
    'dcf_expander': '1  DCF — Iskontolu Nakit Akışı',
    'dcf_title': 'Iskontolu nakit akışı yaklaşımı',
    'dcf_concept': 'Bir şirketin bugünkü değeri tüm gelecekteki nakit akışlarının iskonto edilerek bugüne indirgenmesiyle eşittir. 10 yıl sonraki bir euro bugünkünden daha az değerlidir.',
    'dcf_variables': 'SMNt: t yılında öngörülen SMN | k: Iskonto oranı (AASK), tipik %8-12 | SV: Süreklilik Değeri, toplam değerin %60-80 | n: Tahmin ufku (5-10 yıl)',
    'dcf_usecase': 'Kullanım: Öngörülebilir gelirler ve istikrarlı büyüme — Air Liquide, Microsoft, TotalEnergies.',
    'dcf_warning': 'Duyarlılık: k veya g üzerinde %1 değişiklik değeri %20-40 değiştirebilir. Her zaman kötümser, orta ve iyimser senaryo oluşturun.',
    'dcf_target': 'Uzun vadeli yatırım için referans yöntem',
    'multiples_expander': '2  Piyasa Katları — Karşılaştırmalı Yaklaşım',
    'multiples_title': 'Eşdeğer şirketlerle karşılaştırmalı değerleme',
    'multiples_concept': 'Bir hisse, piyasanın karşılaştırılabilir şirketler için ödemeye hazır olduğu kadar değerlidir. Göreceli değerleme: hissenin rakiplerine göre ucuz mu pahalı mı olduğu araştırılır.',
    'multiples_details': 'F/K (Fiyat/Kazanç): en popüler | FD/FAVÖK: farklı sermaye yapıları için | F/S: kârsız girişimler için | F/SMN: değer yatırımcılarının tercihi',
    'multiples_usecase': 'Kullanım: Homojen sektörler — Bankacılık, Otomotiv, Perakende, Telekom.',
    'multiples_warning': 'Sınırlama: tüm sektör aşırı değerliyse karşılaştırılan hisse de öyle olacaktır. Görece ucuz der, gerçekten ucuz değil.',
    'multiples_target': 'Tarama ve sektör karşılaştırması için hızlı yöntem',
    'gordon_expander': '3  Gordon-Shapiro — DDM (Temettü Indirim Modeli)',
    'gordon_title': 'Temettü Indirim Modeli (DDM)',
    'gordon_concept': 'Hisse daimi bir rant olarak değerlendirilir. Değeri tüm gelecekteki temettülerin iskontolu toplamıdır. Yalnızca düzenli temettü ödeyen şirketlere uygulanır.',
    'gordon_variables': 'T1: Gelecek yıl beklenen temettü = T0 x (1+g) | k: Talep edilen getiri | g: Yıllık sürekli temettü büyümesi | Örnek: T1=2€, k=%8, g=%3 → P=40€',
    'gordon_usecase': "Kullanım: Büyüyen temettülü olgun şirketler — Coca-Cola, L'Oreal, Orange, LVMH.",
    'gordon_warning': 'Sınırlama: k küçük veya eşit g olursa formül patlar. Temettü ödemeyen şirketler için çalışmaz.',
    'gordon_target': 'Pasif gelir arayan yatırımcılar için ideal yöntem',
    'anr_expander': '4  NSV — Net Subvansiyonlu Deger (Varlik Yaklasimi)',
    'anr_title': 'Gerçek net varlık değeri',
    'anr_concept': 'Tüm varlıklar satılıp borçlar ödenseydi hissedarlara ne kalırdı? Gelir tablosu yerine bilançoya bakılır. Değer yatırımının babası Benjamin Graham yöntemidir.',
    'anr_variants': 'Defter Değeri (F/DD): basit muhasebe versiyonu | Graham Net-Net: net dönen varlıklarının altında hisse | Gayrimenkul NSV: mülkler piyasa değerine göre',
    'anr_usecase': 'Kullanım: Holding şirketleri, gayrimenkul (GYO), ağır sanayi, mali güçlük içindeki şirketler.',
    'anr_warning': 'Sınırlama: gelecekteki kazanç kapasitesini dikkate almaz. Kağıt üzerinde düşük değerli görünebilir ama muazzam nakit üretebilir.',
    'anr_target': 'Derin Değer yöntemi — Benjamin Graham yaklaşımının temeli',
    'convergence_title': 'Yöntemlerin yakınsaması: en güvenilir sinyal',
    'convergence_body': 'Birden fazla yöntem aynı adil değere yakınsadığında güven çok daha güçlüdür. Büyük sapma yüksek belirsizliğe veya gözden geçirilmesi gereken bir varsayıma işaret eder.',
    'wacc_expander': 'AASK — Iskonto Oranı (yalnızca DCF)',
    'wacc_title': 'Ağırlıklı Ortalama Sermaye Maliyeti (AASK)',
    'wacc_concept': 'AASK, gelecekteki nakit akışlarının bugüne indirgeme oranıdır. Ne kadar yüksekse hesaplanan değer o kadar düşük. %1 değişiklik değerlemeyi %15-30 değiştirebilir.',
    'wacc_variables': 'kö = Risksiz oran + beta × Piyasa primi | kb = borç maliyeti | v = vergi oranı | beta = piyasaya göre göreli volatilite',
    'wacc_ranges': 'Büyük istikrarlı (beta≈0.8): %7-9 | Döngüsel (beta≈1.2): %10-12 | Küçük cap (beta≈1.5): %13-16 | Yüksek borçlu: +%1-3',
    'wacc_auto': "SigmaScope AASK'ı otomatik tahmin eder: Risksiz oran (%4) + beta × %5 + borç spreadi. Tahmin gösterge niteliğindedir.",
    'wacc_target': 'Duyarlılık: k üzerinde %1 → değerde %15-25',
    'g_expander': 'g — Sürekli Büyüme Oranı (yalnızca DCF)',
    'g_title': 'Terminal büyüme oranı (süreklilik değeri)',
    'g_concept': "Süreklilik değeri toplam DCF değerinin %60-80'ini oluşturur. g parametresi en hassas olanıdır. Her zaman AASK'tan düşük olmalıdır, aksi takdirde formül sonsuz değerler üretir.",
    'g_rules': 'g nominal GSYİH büyümesini asla geçmemeli (≈ %2-3) | Teknoloji: %2.5-3 | Ağır sanayi: %1-1.5 | Gelişen piyasalar: %3-4',
    'g_warning': "AASK %10 ile g %4, g %2'ye kıyasla 2x daha yüksek SV verir. Her zaman 3 senaryo test edin: kötümser (%1), orta (%2.5), iyimser (%4).",
    'g_target': "Altın kural: g AASK'tan ve GSYİH büyümesinden düşük olmalı",
    'k_gordon_expander': 'k — Gordon-Shapiro Gerekli Getiri (yalnızca DDM)',
    'k_gordon_title': 'Hissedar tarafından talep edilen getiri',
    'k_gordon_concept': "Gordon-Shapiro'da k, yatırımcının hisseyi tutmak için talep ettiği minimum getiridir. DCF'deki AASK ile aynı rolü oynar, yalnızca özkaynaklara uygulanır.",
    'k_gordon_calibration': 'Temkinli yatırımcı: k = %5-7 | Dengeli: k = %7-9 | Büyüme: k = %9-12 | Mutlak kısıt: k > g',
    'k_gordon_warning': 'Örnek: k=%8, g=%3 → spread=5 | k=%6, g=%4 → spread=2: aynı temettüyle değer 2.5x yüksek. k-g spreadi küçükken duyarlılık son derece yüksektir.',
    'k_gordon_target': 'Duyarlılık: k-g spreadi yarıya inerse değer iki katına çıkar',
    'horizon_expander': 'DCF Ufku — Projeksiyon yılı sayısı (yalnızca DCF)',
    'horizon_title': 'Açık projeksiyon ufku',
    'horizon_concept': "Ufuk, süreklilik değeri uygulanmadan önce SMN'nin yıl yıl öngörüldüğü dönemdir. Kısa ufuk yüksek büyümeli şirketlerin değerini düşük tahmin eder.",
    'horizon_reco': '5 yıl: döngüsel sektörler | 10 yıl: standart önerilen | 15-20 yıl: kalıcı avantajlı yüksek büyüme',
    'horizon_warning': '10 yılın ötesinde tahmin doğruluğu hızla azalır. Ufku uzatmak yerine birden fazla senaryo oluşturun.',
    'horizon_target': 'Önerilen varsayılan: çoğu durum için 10 yıl',
    'sensitivity_title': 'Duyarlılık tablosu — Parametre etkisi',
    'sensitivity_caption': 'Güçlü artış olarak işaretlenenler en hassas parametrelerdir — yatırım kararı öncesi kötümser/iyimser senaryolarda test edin.',
    'sensitivity_param': 'Parametre',
    'sensitivity_method': 'Yöntem',
    'sensitivity_effect': 'Artışın etkisi',
    'sensitivity_range': 'Tipik aralık',

    'hero_pp_desc_inline': '— portföyünüzü doğrudan içe aktarın (XML dosyası)',
    'stat_indices_loaded': 'Yüklü endeksler ({lbl})',
    'stat_none_loaded': 'Hiçbiri yüklenmedi',
    'qs_step1': "<strong>⚙️ Yapılandırma</strong> sayfasına gidin ve Wikipedia'dan bir endeks (S&P 500, CAC 40…) yükleyin.",
    'qs_step2': '<strong>📈 Hisse analizi</strong>ni açın, bir sembol girin (örn. <code>AAPL</code>, <code>BNP.PA</code>) ve analizi başlatın.',
    'qs_step3': '<strong>Temel karne</strong>yi ve <strong>sigma konumunu</strong> inceleyerek hisseyi değerlendirin.',
    'qs_step4': 'İlginç hisseleri takip etmek için <strong>⭐ İzleme listenize</strong> ekleyin.',
    'qs_step5': 'Tüm bir endeksi tek tıkla taramak için <strong>🔭 Sigma Tarayıcı</strong>yı kullanın.',
    'sigma_zone1_label': 'Düşük aşırılık (< −1.75σ)',
    'sigma_zone1_desc': 'İstatistiksel fırsat bölgesi — potansiyel alım fırsatı',
    'sigma_zone2_label': 'Zayıf trend (−0.75 ile −1.25σ)',
    'sigma_zone2_desc': 'Aşağı kanal — Bear market',
    'sigma_zone3_label': 'Nötr bölge (−0.25 ile +0.25σ)',
    'sigma_zone3_desc': 'Denge — net bir yön yok',
    'sigma_zone4_label': 'Güçlü trend (+0.75 ile +1.25σ)',
    'sigma_zone4_desc': 'İdeal yukarı kanal — Bull run',
    'sigma_zone5_label': 'Yüksek aşırılık (> +1.75σ)',
    'sigma_zone5_desc': 'Aşırı ısınma — ortalamaya dönüş riski',
    'roadmap_high': '🔴 Yüksek öncelik',
    'roadmap_study': '🟢 İnceleniyor',
    'roadmap_caption': '💡 Aşağıdaki **Öneriler** bölümünde en çok neyin işinize yarayacağını söyleyin!',
    'stats_rating_label': 'Puanınız',
    'stats_saas_label': 'SigmaScope tam bir web sitesine dönüştürülmeli mi?',
    'stats_saas_yes': '✅ Evet, tam bir web sitesine dönüştür',
    'stats_saas_no': '❌ Hayır, Streamlit uygulaması yeterli',
    'feedback_msg_label': 'Mesajınız',
    'analyse_params_expander': '🔍 Analiz parametreleri',
    'analyse_company_expander': '🏢 Şirket bilgileri',
    'analyse_trend_expander': '📈 Trend Analizi',
    'analyse_tech_expander': '📊 Teknik Analiz',
    'analyse_fv_expander': '💰 Tarihsel Gerçek Değer',
    'analyse_score_expander': '📊 Temel Karne ve Genel Skor',
    'analyse_hist_expander': '📊 Tarihsel Temel Göstergeler',
    'analyse_position_caption': '📍 Güncel konum: **{sigma}σ** — {zone}',
    'analyse_yahoo_link_text': "Yahoo Finance'te görüntüle → {ticker}",
    'analyse_ma_caption': 'HO {ma1} / {ma2} / {ma3}',
    'analyse_no_data_ticker': 'Bu sembol için veri bulunamadı.',
    'analyse_loading_fund': 'Temel veriler yükleniyor…',
    'analyse_indice_none': '-- Hiçbiri --',
    'scorecard_global_label': '7 temel kritere dayalı **genel skor**: Gelir büyümesi, SMN büyümesi, ROIC, SMN marjı, Borç/SMN, PEG, F/DD.',
    'scorecard_obj': 'Hedef:',
    'scorecard_cat_growth': '📈 Büyüme Göstergeleri',
    'scorecard_cat_profit': '💰 Kârlılık Göstergeleri',
    'scorecard_cat_valuation': '⚖️ Değerleme Göstergeleri',
    'scorecard_cat_solidity': '🏦 Finansal Güç',
    'scorecard_metric_rev': 'Gelir büyümesi',
    'scorecard_metric_fcf': 'SMN büyümesi',
    'scorecard_metric_roic': 'ROIC',
    'scorecard_metric_roe': 'ROE',
    'scorecard_metric_fcfm': 'SMN marjı',
    'scorecard_metric_pe': 'F/K',
    'scorecard_metric_peg': 'PEG',
    'scorecard_metric_pb': 'F/DD',
    'scorecard_metric_debt': 'Borç/SMN',
    'scorecard_metric_pfcf': 'F/SMN',
    'company_profile_title': '🏢 Profil',
    'company_name_lbl': 'Ad:',
    'company_sector_lbl': 'Sektör:',
    'company_industry_lbl': 'Endüstri:',
    'company_country_lbl': 'Ülke:',
    'company_employees_lbl': 'Çalışan sayısı:',
    'company_dividend_title': '💰 Temettü',
    'company_annual_div': 'Yıllık temettü:',
    'company_yield': 'Getiri:',
    'company_exdate': 'Ex-tarih:',
    'company_next_payment': 'Sonraki ödeme:',
    'company_none': 'Yok',
    'company_rec_title': '📋 Analist Tavsiyeleri',
    'company_rec_unknown': 'Bilinmeyen format',
    'company_rec_none': 'Tavsiye mevcut değil',
    'chart_revenue_name': 'Gelir (Mrd)',
    'chart_fcf_name': 'Serbest Nakit Akışı (Mrd)',
    'chart_trend_ca': 'Gelir trendi',
    'chart_rev_growth': '📊 Gelir vs SMN büyümesi (%)',
    'chart_cours': 'Fiyat',
    'wl_stocks_followed': '**{n} hisse takip ediliyor** — Canlı veriler (fiyat) + temel bilgiler (1s önbellek) · {uid}',
    'wl_select_label': '📋 Aktif izleme listesi',
    'wl_col_price_native': 'Fiyat',
    'wl_col_price_eur': 'Fiyat EUR (€)',
    'wl_col_change_j': 'Günlük değ. (%)',
    'wl_col_sigma_pos': 'σ Konumu',
    'wl_col_pru_eur': 'Ort. maliyet (€)',
    'wl_col_pru_gap': '+/- Ort. maliyet (%)',
    'wl_col_analyse_ico': '📈',
    'wl_col_remove_ico': '🗑️ Çıkar',
    'wl_analyse_help': 'Bireysel analiz başlat',
    'wl_remove_help': 'İzleme listesinden çıkarmak için işaretleyin',
    'wl_ticker_help': 'Yahoo Finance sembolü',
    'wl_price_help': 'Yerel para biriminde güncel fiyat',
    'wl_price_eur_help': "EUR'ya çevrilmiş fiyat",
    'wl_change_help': 'Günlük değişim',
    'wl_score_help': 'Temel skor /10 (A→F notu)',
    'wl_sigma_help': 'Log regresyona göre sigma konumu',
    'wl_pru_help': 'EUR cinsinden ortalama alış maliyeti',
    'wl_pru_gap_help': 'Güncel fiyat (€) ile ortalama maliyet arasındaki fark',
    'wl_refresh_help': 'Önbelleği temizle ve piyasa verilerini yeniden yükle',
    'wl_period_label': 'Zaman ufku',
    'wl_empty_wl': '📋 İzleme listesi boş',
    'wl_n_stocks': '📋 {n} hisse: {tickers}',
    'wl_data_errors_caption': '⚠️ Veri mevcut değil: {tickers}',
    'wl_no_pending': 'Bekleyen işlem yok.',
    'wl_close_btn': 'Kapat',
    'wl_dialog_add_label_inline': '**`{ticker}` ekle** ({company}) izleme listesine:',
    'wl_dialog_target_label': 'Hedef izleme listesi',
    'wl_dialog_add_btn': '✅ Ekle',
    'wl_dialog_cancel': '❌ İptal',
    'wl_dialog_remove_label': '**`{ticker}`** sembolünü **{name}** listesinden çıkar?',
    'wl_dialog_remove_btn': '🗑️ Çıkar',
    'wl_toast_added': '⭐ {ticker} **{name}** listesine eklendi!',
    'wl_toast_removed': '❌ {ticker} izleme listesinden çıkarıldı',
    'wl_already_in': '⚠️ `{ticker}` zaten **{name}** listesinde.',
    'wl_create_form_label': 'Yeni izleme listesi adı',
    'wl_delete_confirm_warn': '⚠️ **{name}** izleme listesini ve tüm kayıtlarını sil?',
    'wl_autosave_caption': '💾 **{name}** — otomatik kaydediliyor',
    'wl_import_xml_help': "Portfolio Performance'dan portföy içe aktar (.xml)",
    'pp_step1_title': '📂 Yükleme',
    'pp_step2_title': '🏦 Hesap',
    'pp_step3_title': '✅ Onay',
    'pp_upload_md': '**Portfolio Performance XML dosyasını yükleyin**',
    'pp_upload_cap': "Portfolio Performance'da *Dosya → Farklı kaydet…* menüsü.",
    'pp_upload_info': '👆 Yukarıdan Portfolio Performance dosyanızı (.xml) seçin.',
    'pp_parse_err': '❌ Ayrıştırma hatası: {e}',
    'pp_select_md': '**İçe aktarılacak hesabı seçin**',
    'pp_positions_cap': '📊 **{name}** listesinde **{n} pozisyon**:',
    'pp_pru_note': 'ℹ️ Ortalama maliyetler EUR cinsindendir ve olduğu gibi içe aktarılacaktır.',
    'pp_more_pos': '… ve {n} pozisyon daha gösterilmiyor.',
    'pp_confirm_md': '**İzleme listesini adlandırın ve içe aktarmayı onaylayın**',
    'pp_wl_name_label': 'İzleme listesi adı',
    'pp_wl_name_help': 'Bu adla yeni bir izleme listesi oluşturulacak (varsa değiştirilecek).',
    'pp_wl_exists_warn': '⚠️ **{name}** izleme listesi zaten var — içeriği **değiştirilecek**.',
    'pp_wl_new_info': '✨ **{name}** adında yeni bir izleme listesi oluşturulacak.',
    'pp_import_note': '📥 **{account}** hesabından **{n} pozisyon** içe aktarılacak: Sembol, Ad, EUR ort. maliyet.',
    'pp_name_empty': 'Ad boş olamaz.',
    'pp_import_toast': '✅ **{name}** listesine {n} pozisyon içe aktarıldı!',
    'comp_params_expander': '🔍 Karşılaştırma parametreleri',
    'comp_select_label': '**Karşılaştırılacak hisseleri seçin**',
    'comp_period_label_bold': '**📅 Zaman ufku**',
    'comp_selected_cap': '**Seçilen hisseler:** {tickers}',
    'comp_btn': '📊 Karşılaştır',
    'comp_no_data': 'Veri mevcut değil.',
    'comp_table_subtitle': '📋 Performans tablosu',
    'comp_tip_caption': '💡 **📈 Analiz** için kutucuğu işaretleyin · **⭐ İzleme listesi** için ekle/çıkar',
    'comp_analyse_col_help': 'Bireysel analiz başlat',
    'comp_wl_col_help': 'İzleme listesine ekle/çıkar',
    'comp_configure_msg': '👆 Hisseleri seçin, ardından **📊 Karşılaştır** butonuna tıklayın.',
    'screener_sigma_info': '🔄 **{index}** endeksinden **{n}** hisse taranıyor, dönem: **{period}** — bölgeler: **{zones}**',
    'screener_sigma_errors_cap': '⚠️ Veri mevcut değil: {tickers}',
    'screener_sigma_log_cap': '⚠️ % değişim log ölçeğiyle uyumsuz',
    'screener_sigma_position_lbl': 'Konum:',
    'screener_sigma_zone_lbl': 'Bölge:',
    'screener_sigma_period_lbl': 'Dönem:',
    'screener_no_index_warn': '⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.',
    'screener_sigma_no_result': 'Seçilen bölgeler için hisse bulunamadı.',
    'screener_multi_info': '🔄 **{index}** endeksinden **{n}** hisse taranıyor — veriler yükleniyor…',
    'screener_multi_errors_cap': '⚠️ Hatalar: {tickers}',
    'screener_multi_tip': '💡 Analiz için **📈 Analiz Et** · İzleme listesi için **⭐ IL** kutucuğunu işaretleyin',
    'screener_multi_found_msg': '✅ **{n} hisse** kriterlerinize uyuyor  •  {index}  •  {period}  •  *{total} yüklendi — gerçek zamanlı filtreleme*',
    'screener_multi_charts_sub': '📈 Grafikler — {n} seçili hisse',
    'screener_multi_no_sigma': 'ℹ️ Sigma bölgesi seçilmedi = tüm bölgeler kabul edildi.',
    'screener_multi_no_index': '⚠️ Yüklü endeks yok. ⚙️ Yapılandırma sayfasına gidin.',
    'screener_multi_configure': '👆 Filtreleri ayarlayın, ardından **🚀 Tarayıcıyı başlat** butonuna tıklayın.',
    'screener_multi_score_col': 'Skor:',
    'config_preview_select': 'Bileşenleri göster',
    'config_wiki_loading': '{label} yükleniyor…',
    'config_wiki_ok': '✅ {label} için {n} bileşen yüklendi ve kaydedildi.',
    'config_wiki_err': 'Kazıma hatası: {e}',
    'config_cache_help': '2 saatten eski önbellek girişlerini siler',
    'config_purge_help': 'Kalıcı silme — geri alınamaz',
    'config_purge_ok': '✅ {n} pasif izleme listesi silindi.',
    'config_purge_none': 'ℹ️ Silinecek pasif izleme listesi yok.',
    'config_private_count': '{n} özel mesaj',
    'config_admin_pwd_label': 'Yönetici şifresi',
    'wl_col_remove_help': 'İzleme listesinden çıkarmak için işaretleyin',

}
