# ============================================================
# SIGMASCOPE — Translation dictionary ENGLISH
# ============================================================

TRANSLATIONS = {

    # ── Language ─────────────────────────────────────────────
    "lang_selector_label": "🌐 Langue / Language",
    "lang_fr": "🇫🇷 Français",
    "lang_en": "🇬🇧 English",

    # ── Sidebar ──────────────────────────────────────────────
    "sidebar_title":        "🚀 SigmaScope by jp",
    "sidebar_nav":          "### 🗂️ Navigation",
    "sidebar_indices":      "**📂 Loaded indices**",
    "sidebar_no_index":     "⚠️ No index loaded.\nGo to ⚙️ Configuration.",
    "sidebar_valeurs":      "values",
    "sidebar_stop":         "⏹️ Stop application",
    "sidebar_stop_help":    "Stop the Streamlit server",
    "sidebar_stopping":     "Stopping…",

    # ── Pages navigation ─────────────────────────────────────
    "page_presentation":    "🏠 Overview",
    "page_analyse":         "📈 Stock analysis",
    "page_watchlists":      "⭐ Watchlists",
    "page_comparaison":     "🔀 Peer comparison",
    "page_screener_sigma":  "🔭 Sigma Screener",
    "page_screener_multi":  "🎛️ Multi-criteria screener",
    "page_explications":    "📖 Documentation",
    "page_configuration":   "⚙️ Configuration",

    # ── Page Overview — Hero ─────────────────────────────────
    "hero_tagline":         "The all-in-one quantitative stock analysis platform",
    "hero_tagline2":        "Log regression · Fundamental analysis · Screener · DCF valuation",
    "hero_version":         "✨ Version 24 — by jp",
    "hero_pp_compat":       "🤝 Compatible with",
    "hero_pp_desc":         "— direct import of your portfolio (XML file)",

    # ── Page Overview — Features ─────────────────────────────
    "feat_title":           "### 🧩 Main features",
    "feat_open_analyse":    "→ Open Stock analysis",
    "feat_open_watchlist":  "→ Open Watchlists",
    "feat_open_comparaison":"→ Open Peer comparison",
    "feat_open_screener_s": "→ Open Sigma Screener",
    "feat_open_screener_m": "→ Open Multi-criteria screener",
    "feat_open_valorisation":"→ See in Stock analysis",

    # ── Page Overview — Stats badges ─────────────────────────
    "stat_modules":         "Analysis modules",
    "stat_indices":         "Loaded indices",
    "stat_tickers":         "Pre-loaded tickers (∞ via Yahoo Finance)",
    "stat_methods":         "Valuation methods",
    "stat_sigma_zones":     "Sigma zones detected",

    # ── Page Overview — Quick start ──────────────────────────
    "quickstart_title":     "### 🚀 Quick start",
    "sigma_zones_title":    "### 📐 Understanding sigma zones",

    # ── Page Overview — Roadmap ──────────────────────────────
    "roadmap_expander":     "🛠️ Roadmap & upcoming features",
    "roadmap_title":        "#### 🚧 In development / coming soon",
    "roadmap_legend_high":  "🔴 High priority",
    "roadmap_legend_study": "🟢 Under consideration",
    "roadmap_caption":      "💡 Tell me what would be most useful to you in the **Suggestions** section below!",
    "roadmap_item1_title":  "Fair value calculation review",
    "roadmap_item1_desc":   "In-depth review of **DCF, Gordon-Shapiro, Multiples and NAV** methods — verifying formula consistency, default assumptions and results against financial valuation standards.",
    "roadmap_item2_title":  "Google authentication",
    "roadmap_item2_desc":   "Replace the anonymous token with a **real Google account** — to access your watchlists from any device. Leave me a comment if this matters to you 👇",
    "roadmap_item3_title":  "Data export",
    "roadmap_item3_desc":   "Export watchlists and analysis results to **CSV / Excel**. Leave me a comment if you need this 👇",
    "roadmap_item4_title":  "Advanced screener",
    "roadmap_item4_desc":   "Add technical filters (RSI, Bollinger) to the multi-criteria screener. Leave me a comment if this would be useful 👇",
    "roadmap_item5_title":  "Yahoo Finance stability",
    "roadmap_item5_desc":   "Yahoo Finance rate limiting can cause intermittent errors. An official replacement API is under consideration. Leave me a comment if you often face this issue 👇",
    "roadmap_item6_title":  "Migration to a full website",
    "roadmap_item6_desc":   "If usage justifies it, a migration to a **full web application** (FastAPI + React) is being considered. Vote below and leave a comment 👇",

    # ── Page Overview — Stats & ratings ──────────────────────
    "stats_expander":           "📊 Usage statistics",
    "stats_users":              "Unique users",
    "stats_sessions":           "Total sessions",
    "stats_duration":           "Avg. session duration",
    "stats_rating":             "reviews",
    "stats_saas_vote":          "Website migration vote",
    "stats_rating_title":       "#### ⭐ Rate this app",
    "stats_your_note":          "Your rating",
    "stats_saas_question":      "Should SigmaScope be converted to a full website?",
    "stats_saas_yes":           "✅ Yes, convert to a full website",
    "stats_saas_no":            "❌ No, the Streamlit app is fine",
    "stats_save_btn":           "💾 Save my review",
    "stats_save_ok":            "✅ Thank you! Rating: {stars} — SaaS vote: {vote}",
    "stats_save_oui":           "Yes",
    "stats_save_non":           "No",
    "stats_save_err":           "❌ Error while saving.",

    # ── Page Overview — Suggestions ──────────────────────────
    "feedback_expander":        "💬 Suggestions & improvements",
    "feedback_title":           "#### 📝 Leave a message",
    "feedback_visibility":      "Message visibility",
    "feedback_public":          "🌐 Public — visible to everyone",
    "feedback_private":         "🔒 Private — visible to administrator only",
    "feedback_caption_private": "🔒 This message will only be visible to the administrator.",
    "feedback_caption_public":  "🌐 This message will be visible to all users.",
    "feedback_placeholder":     "E.g.: Add a MACD indicator, improve the screener page...",
    "feedback_send_btn":        "📤 Send",
    "feedback_ok_private":      "✅ Private message sent to the administrator, thank you!",
    "feedback_ok_public":       "✅ Public message sent, thank you!",
    "feedback_err":             "❌ Error while sending.",
    "feedback_empty":           "⚠️ Message cannot be empty.",
    "feedback_community_title": "#### 💡 Community suggestions",
    "feedback_none":            "No suggestions yet — be the first!",

    # ── Footer ───────────────────────────────────────────────
    "footer_text":  "⚡ SigmaScope uses <strong style=\"color:#4C9BE8;\">Yahoo Finance</strong> as data source · Designed for quantitative analysis · <em>Not investment advice</em>",

    # ── Stock analysis page ───────────────────────────────────
    "analyse_title":            "📈 Stock analysis",
    "analyse_params_expander":  "🔍 Analysis parameters",
    "analyse_ticker_label":     "Ticker / Company",
    "analyse_ticker_help":      "Filtering search across all loaded indices",
    "analyse_ticker_placeholder":"Type a ticker (AAPL) or company name (Apple)…",
    "analyse_ticker_manual":    "Manual ticker",
    "analyse_ticker_manual_ph": "e.g.: AAPL, BNP.PA…",
    "analyse_indice_label":     "Choose an index / watchlist",
    "analyse_composant_label":  "Component ({n} values)",
    "analyse_no_index":         "⚠️ No data. Go to ⚙️ Configuration.",
    "analyse_choose_index":     "— choose an index first —",
    "analyse_period_label":     "Period",
    "analyse_ticker_selected":  "Selected ticker:",
    "analyse_launch_btn":       "🚀 Run Analysis",
    "analyse_loading":          "Loading data…",
    "analyse_no_data":          "No data available for this ticker.",
    "analyse_error":            "Error: {e}",
    "analyse_configure_first":  "👆 Configure a ticker above then click **🚀 Run Analysis**.",

    # ── Analysis — sub-sections ───────────────────────────────
    "analyse_tech_expander":    "📊 Technical Analysis",
    "analyse_fair_expander":    "💰 Historical Fair Value",
    "analyse_score_expander":   "📊 Fundamental Scorecard & Global Score",
    "analyse_histo_expander":   "📊 Historical Fundamental Indicators",
    "analyse_info_expander":    "🏢 Company information",
    "analyse_trend_expander":   "📈 Trend Analysis",
    "analyse_adv_params":       "⚙️ Advanced parameters",

    # ── Analysis — Technical ─────────────────────────────────
    "tc_period_warning":        "⚠️ Period limited to **{period}** for granularity {interval}.",
    "tc_no_data":               "No data available for this ticker.",
    "tc_chart_err":             "Error loading technical chart: {e}",

    # ── Analysis — Fair Value ─────────────────────────────────
    "fv_no_data":               "ℹ️ Insufficient data to compute fair value with this method ({method}).",
    "fv_no_fetch":              "⚠️ Unable to retrieve data to compute fair value.",

    # ── Watchlists ────────────────────────────────────────────
    "wl_title":                 "⭐ My Watchlists",
    "wl_info":                  "🔑 **Your watchlists are saved** in a secure database, identified by a unique anonymous token linked to your browser (token: `{uid}`).  \n📌 **Bookmark this page** to access your watchlists anytime — the URL contains your token.  \n⚠️ **Expiry**: if you don't return for **30 days**, your watchlists will be automatically deleted from the database.",
    "wl_manage_expander":       "🗂️ Watchlist management",
    "wl_active_label":          "📋 Active watchlist",
    "wl_new_btn":               "➕ New",
    "wl_delete_btn":            "🗑️ Delete",
    "wl_delete_help":           "Delete watchlist '{name}'",
    "wl_import_btn":            "📥 Import",
    "wl_import_help":           "Import a portfolio from Portfolio Performance (.xml)",
    "wl_delete_confirm_msg":    "⚠️ Delete watchlist **{name}** and all its entries?",
    "wl_delete_confirm_btn":    "🗑️ Confirm deletion",
    "wl_delete_cancel_btn":     "❌ Cancel",
    "wl_autosave":              "💾 **{name}** — auto-saved",
    "wl_add_expander":          "➕ Add a stock manually",
    "wl_add_ticker_label":      "Ticker",
    "wl_add_ticker_ph":         "e.g.: AAPL, BNP.PA",
    "wl_add_btn":               "➕ Add",
    "wl_add_ok":                "✅ {ticker} added to watchlist!",
    "wl_add_duplicate":         "{ticker} is already in the watchlist.",
    "wl_add_empty":             "Enter a ticker.",
    "wl_empty_info":            "👆 Your watchlist is empty. Add stocks using the **⭐ Watchlist** button on any page, or manually above.",
    "wl_refresh_btn":           "🔄 Refresh data",
    "wl_data_errors":           "⚠️ Data unavailable for: {tickers}",
    "wl_analyse_tip":           "💡 Check **📈** on the left to launch individual stock analysis",
    "wl_sigma_expander":        "📈 Watchlist chart (sigma positions)",
    "wl_pru_expander":          "💰 Watchlist chart (price vs average cost)",
    "wl_manage2_expander":      "⚙️ Watchlist management",
    "wl_remove_tip":            "💡 Check **🗑️ Remove** to delete a stock from the watchlist",
    "wl_edit_expander":         "✏️ Add a note / purchase price",
    "wl_save_edit_btn":         "💾 Save",
    "wl_edit_ok":               "✅ Updated.",
    "wl_sigma_no_data":         "Sigma data unavailable.",
    "wl_pru_no_data":           "No purchase price entered in this watchlist.",

    # ── Peer comparison ───────────────────────────────────────
    "comp_title":               "🔀 Peer comparison",
    "comp_params_expander":     "🔍 Comparison parameters",
    "comp_selected":            "**Selected stocks:** {tickers}",
    "comp_no_data":             "No data available.",
    "comp_table_title":         "📋 Performance table",
    "comp_tip":                 "💡 Check **📈 Analyse** for individual analysis · Check **⭐ Watchlist** to add/remove",
    "comp_configure_first":     "👆 Select stocks then click **📊 Compare**.",

    # ── Sigma Screener ────────────────────────────────────────
    "screener_sigma_title":     "🔭 Sigma Screener — Scan index stocks",
    "screener_sigma_params":    "🔍 Scan parameters",
    "screener_sigma_no_index":  "⚠️ No index loaded. Go to ⚙️ Configuration.",
    "screener_sigma_launch":    "🔍 Run scan",
    "screener_sigma_scanning":  "🔄 Scanning **{n}** stocks from **{index}** over **{period}** — zones: **{zones}**",
    "screener_sigma_errors":    "⚠️ Unavailable data: {tickers}",
    "screener_sigma_no_result": "No stocks found for the selected zones.",
    "screener_sigma_found":     "✅ **{n} stock(s) found**  •  {index}  •  {period}",
    "screener_sigma_tip":       "💡 Check **📈 Analyse** to launch analysis · Check **⭐ WL** to add/remove from watchlist",
    "screener_sigma_charts":    "📈 Charts — {n} stock(s)",
    "screener_sigma_log_warn":  "⚠️ % variation incompatible with log scale",
    "screener_sigma_select_zone":"👆 Select at least one zone then click **🔍 Run scan**.",

    # ── Multi-criteria screener ───────────────────────────────
    "screener_multi_title":     "🎛️ Multi-criteria screener",
    "screener_multi_params":    "🔍 Screener parameters",
    "screener_multi_no_index":  "⚠️ No index loaded. Go to ⚙️ Configuration.",
    "screener_multi_launch":    "🚀 Run screener",
    "screener_multi_reset":     "↺ Reset filters",
    "screener_multi_no_sigma":  "ℹ️ No sigma zone selected = all zones accepted.",
    "screener_multi_scanning":  "🔄 Scanning **{n}** stocks from **{index}** — loading data…",
    "screener_multi_errors":    "⚠️ Errors on: {tickers}",

    # ── Documentation page ────────────────────────────────────
    "explain_title":            "📖 Indicators & valuation methods guide",
    "explain_scoring_title":    "### 📊 Scoring Indicators",
    "explain_valuation_title":  "### 💰 Valuation: How to compute the Fair Value of a Stock?",
    "explain_params_title":     "### ⚙️ Valuation Parameters Guide",
    "explain_sensitivity_cap":  "💡 Items marked **increases strongly** are the most sensitive parameters — test them in pessimistic/optimistic scenarios before any investment decision.",

    # ── Configuration page ────────────────────────────────────
    "config_title":             "⚙️ Configuration — Index management",
    "config_indices_title":     "📊 Loaded indices status",
    "config_preview_title":     "🔍 Component preview",
    "config_preview_select":    "Show components for",
    "config_choose_index":      "-- Choose an index --",
    "config_no_index":          "ℹ️ No index loaded. Log in as administrator to update.",
    "config_admin_title":       "🔐 Administration",
    "config_admin_caption":     "This section is restricted to the administrator.",
    "config_admin_pwd_ph":      "••••••••",
    "config_admin_login_btn":   "🔑 Access",
    "config_admin_err":         "❌ Incorrect password.",
    "config_admin_ok":          "✅ Administrator mode enabled",
    "config_admin_logout":      "🔓 Logout",
    "config_wiki_expander":     "🔄 Update Wikipedia indices",
    "config_wiki_desc":         "Reload stock index components from Wikipedia.",
    "config_wiki_select":       "Index to update",
    "config_wiki_none":         "-- None --",
    "config_wiki_btn":          "🔄 Update",
    "config_wiki_btn_help":     "Reload this index from Wikipedia",
    "config_wiki_source":       "🌐 Source:",
    "config_wiki_ok":           "✅ {n} components saved for {label}.",
    "config_wiki_err":          "Scraping error: {e}",
    "config_wiki_select_first": "Please select an index first.",
    "config_wiki_loading":      "Loading {label}…",
    "config_sys_expander":      "ℹ️ System information",
    "config_cache_btn":         "🧹 Purge market cache (> 2h)",
    "config_cache_ok":          "✅ Cache purged.",
    "config_private_expander":  "🔒 Private user messages",
    "config_private_none":      "No private messages yet.",
    "config_purge_expander":    "🗑️ Inactive watchlist cleanup",
    "config_purge_caption":     "Deletes watchlists (and their contents) from users who have not logged in for more than 30 days. ⚠️ Irreversible operation.",
    "config_purge_btn":         "🗑️ Purge inactive watchlists (> 30d)",
    "config_purge_ok":          "✅ {n} inactive watchlist(s) deleted.",
    "config_purge_none":        "ℹ️ No inactive watchlists to delete.",

    # ── Portfolio Performance import ──────────────────────────
    "pp_dialog_title":          "📥 Import from Portfolio Performance",
    "pp_step1":                 "📂 Loading",
    "pp_step2":                 "🏦 Account",
    "pp_step3":                 "✅ Confirmation",
    "pp_upload_label":          "**Load the Portfolio Performance XML file**",
    "pp_upload_caption":        "Menu *File → Save as…* in Portfolio Performance.",
    "pp_upload_info":           "👆 Select your Portfolio Performance file (.xml) above.",
    "pp_upload_close":          "❌ Close",
    "pp_upload_err":            "❌ Parse error: {e}",
    "pp_select_label":          "**Choose the account to import**",
    "pp_select_account":        "Account",
    "pp_select_pru_note":       "ℹ️ Average costs are in EUR (Portfolio Performance currency) and will be imported as-is.",
    "pp_next_btn":              "▶️ Next",
    "pp_back_btn":              "◀️ Back",
    "pp_cancel_btn":            "❌ Cancel",
    "pp_confirm_label":         "**Name the watchlist and confirm import**",
    "pp_wl_name_label":         "Watchlist name",
    "pp_wl_name_help":          "A new watchlist will be created with this name (or replaced if it already exists).",
    "pp_wl_exists":             "⚠️ Watchlist **{name}** already exists — its content will be **replaced**.",
    "pp_wl_new":                "✨ A new watchlist **{name}** will be created.",
    "pp_import_btn":            "📥 Import",
    "pp_import_empty_name":     "Name cannot be empty.",
    "pp_import_ok":             "✅ {n} position(s) imported into **{name}**!",

    # ── Watchlist dialog ──────────────────────────────────────
    "wl_dialog_title":          "🗂️ Which watchlist to add this ticker to?",
    "wl_dialog_add_label":      "**Add `{ticker}`** ({company}) to watchlist:",
    "wl_dialog_target":         "Target watchlist",
    "wl_dialog_already":        "⚠️ `{ticker}` is already in **{name}**.",
    "wl_dialog_add_btn":        "✅ Add",
    "wl_dialog_cancel_btn":     "❌ Cancel",
    "wl_dialog_add_ok":         "⭐ {ticker} added to **{name}**!",
    "wl_dialog_remove_msg":     "**Remove `{ticker}`** from watchlist **{name}**?",
    "wl_dialog_remove_btn":     "🗑️ Remove",
    "wl_dialog_remove_ok":      "❌ {ticker} removed from watchlist",
    "wl_btn_add":               "⭐ Watchlist",
    "wl_btn_in":                "✅ Watchlist",
    "wl_btn_add_help":          "Add to watchlist ({name})",
    "wl_btn_remove_help":       "Remove from watchlist ({name})",

    # ── Supabase / connection ─────────────────────────────────
    "supabase_err":             "❌ Cannot connect to Supabase: {e}",

    # ── General ───────────────────────────────────────────────
    "min_suffix":               "min",
    "values_suffix":            "values",
    "loading":                  "Loading…",
    "error_prefix":             "Error: ",
}
